### PR TITLE
Fix bug: mysql statement leak

### LINKED ISSUE #1626: [Bug] mysql 后端运行一段时间可能内存泄漏
### Bug Type (问题类型)

_No response_

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql nodes, HDD or SSD 
- OS: 8 CPUs, 32 G RAM, Centos 7.x 
- Data Size:  50W vertices, 130W edges 

### 1.参数配置说明：
1. backend后端mysql  实际数据量 顶点数 50W 边数量 130W
2. 有个业务进程会对huge CRUD，大概的读写 每分钟2000左右 大部分是read  
3. jvm配置：
 java -server 
-Dname=HugeGraphServer 
-Dlog4j.configurationFile=/scripts/hugegraph-0.11.2/conf/log4j2.xml 
-Djava.security.manager=com.baidu.hugegraph.security.HugeSecurityManager 
-Xms16g -Xmx16g 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:HeapDumpPath=/scripts/hugegraph-0.11.2/logs 
-XX:+UseGCLogFileRotation 
-XX:GCLogFileSize=10M 
-XX:NumberOfGCLogFiles=3 
-Xloggc:/scripts/hugegraph-0.11.2/logs/gc.log 
-XX:+PrintHeapAtGC 
-XX:+PrintGCDetails 
-XX:+PrintGCDateStamps 
-XX:+UseG1GC 
-XX:MaxGCPauseMillis=1000 
-XX:+ParallelRefProcEnabled 
-XX:InitiatingHeapOccupancyPercent=50 
-XX:G1RSetUpdatingPauseTimePercent=5 
4.顶点边的缓存配置：
hugegraph.properties：开启了l2 堆外
     vertex.cache_type=l2
     vertex.cache_expire=300
     edge.cache_type=l2
     edge.cache_expire=300
### 2.期望表现
1.在发生老年代 GC 时，可以回收掉一部分对象，使得老年代使用量不是持续走高。(实际运行一段时间后高居不下最后FGC，时长高达43s)

### 3.实际情况
gc

jmap统计对象数据：
image
存活对象：
f0abcbe2ba279b0fb74316a9ba99ab0

GC日志：
[gc.log.zip](https://github.com/hugegraph/hugegraph/files/7451158/gc.log.zip)

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by z7658329**
Fix bug: mysql statement leak

fix #1626

### CODE REVIEW

File: hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java [hunk 1]
```diff
@@ -196,21 +197,22 @@ private PaloFile getOrCreate(String table) {
...
+                    return new PaloLoadInfo(resultSet);
                 }
                 throw new BackendException("Non-exist load label '%s'", label);
             } catch (SQLException e) {
                 throw new BackendException("Failed to fetch load info " +
                                            "for label '%s'", e, label);
+            } finally {
+                if (resultSetWrapper != null) {
+                    resultSetWrapper.close();
+                }
```
Comment (javeme) [inline hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java:215]: seems lack of ResultSetWrapper file

**Review by javeme — COMMENTED** [review]
Looks good, thank you for your contribution.

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java [hunk 2]
```diff
@@ -65,8 +65,8 @@ protected final boolean fetch() {
         }
 
         try {
-            while (!this.resultSetWrapper.getResultSet().isClosed() && this.resultSetWrapper.getResultSet().next()) {
-                MysqlBackendEntry entry = this.row2Entry(this.resultSetWrapper.getResultSet());
+            while (!this.results.isClosed() && this.results.next()) {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java:68]: move `!this.results.isClosed()` into next() method

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    public ResultSetWrapper(ResultSet resultSet, Statement statement) {
+        this.resultSet = resultSet;
+        this.statement = statement;
+    }
+
+    public boolean next() throws SQLException {
+        return resultSet.next();
+    }
+
+    public boolean isClosed() throws SQLException {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:23]: merge into next()

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+            if (statement != null) {
+                statement.close();
+            }
+        } catch (SQLException e) {
+            throw new BackendException(
+                    "Failed to close resultSet and statement", e);
+        }
+    }
+
+    public ResultSet getResultSet() {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:42]: keep resultSet() style

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+        return resultSet;
+    }
+
+    public void setResultSet(ResultSet resultSet) {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:46]: remove it

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+        this.resultSet = resultSet;
+    }
+
+    public Statement getStatement() {
+        return statement;
+    }
+
+    public void setStatement(Statement statement) {
+        this.statement = statement;
+    }
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:56]: remove them

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+import com.baidu.hugegraph.backend.BackendException;
+
+import java.sql.ResultSet;
+import java.sql.SQLException;
+import java.sql.Statement;
+
+public class ResultSetWrapper {
+
+    private ResultSet resultSet;
+    private Statement statement;
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:12]: set final

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java [hunk 8]
```diff
@@ -473,9 +474,15 @@ public void reset() {
...
 
-        public ResultSet select(String sql) throws SQLException {
+        public ResultSetWrapper select(String sql) throws SQLException {
             assert this.conn.getAutoCommit();
-            return this.conn.createStatement().executeQuery(sql);
+            try {
+                Statement statement = this.conn.createStatement();
+                ResultSet rs = statement.executeQuery(sql);
+                return new ResultSetWrapper(rs, statement);
+            } catch (SQLException sqlException) {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java:483]: SQLException e

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java [hunk 9]
```diff
@@ -473,9 +474,15 @@ public void reset() {
             }
         }
 
-        public ResultSet select(String sql) throws SQLException {
+        public ResultSetWrapper select(String sql) throws SQLException {
             assert this.conn.getAutoCommit();
-            return this.conn.createStatement().executeQuery(sql);
+            try {
+                Statement statement = this.conn.createStatement();
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java:480]: move out of try-catch

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java [hunk 10]
```diff
@@ -473,9 +474,15 @@ public void reset() {
...
+                ResultSet rs = statement.executeQuery(sql);
+                return new ResultSetWrapper(rs, statement);
+            } catch (SQLException sqlException) {
+                throw sqlException;
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java:484]: close statement if exception occurred when executeQuery()

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTables.java [hunk 11]
```diff
@@ -108,8 +108,11 @@ public long getCounter(Session session, HugeType type) {
 
             String select = String.format("SELECT ID FROM %s WHERE %s = '%s';",
                                           this.table(), schemaCol, type.name());
+            ResultSetWrapper results = null;
             try {
-                ResultSet resultSet = session.select(select);
+                results = session.select(select);
+                ResultSet resultSet = results.getResultSet();
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTables.java:114]: ResultSet rs

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java [hunk 12]
```diff
@@ -66,7 +66,7 @@ protected final boolean fetch() {
 
         try {
             while (!this.results.isClosed() && this.results.next()) {
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java:68]: can remove `!this.results.isClosed() &&` since done in results.next()

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+            if (this.resultSet != null) {
+                this.resultSet.close();
+            }
+
+            if (this.statement != null) {
+                this.statement.close();
+            }
+        } catch (SQLException e) {
+            throw new BackendException(
+                    "Failed to close resultSet and statement", e);
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:34]: align with "new" and keep "ResultSet and Statement"

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+        }
+    }
+
+    public ResultSet resultSet() {
+        return resultSet;
+    }
+
```
Comment (zhoney) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:41]: delete empty line

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java (hunk 13 above)
Comment (zhoney) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:34]: Failed to close resultSet or Statement

also prefer align " with BackendException in prior line

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java [hunk 15]
```diff
@@ -0,0 +1,42 @@
...
+    public void close() {
+        try {
+            if (this.resultSet != null) {
+                this.resultSet.close();
+            }
+
+            if (this.statement != null) {
+                this.statement.close();
+            }
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java:31]: move to finally-block

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java [hunk 16]
```diff
@@ -196,16 +197,10 @@ private PaloFile getOrCreate(String table) {
...
-                result = this.select(sql);
-            } catch (SQLException e) {
-                throw new BackendException("Failed to fetch load info " +
-                                           "for label '%s'", e, label);
-            }
-            try {
-                if (result.next()) {
-                    return new PaloLoadInfo(result);
+            try (ResultSetWrapper results = this.select(sql)){
+                ResultSet resultSet = results.resultSet();
```
Comment (javeme) [inline hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java:201]: also keep `ResultSet rs`

**Review by javeme — APPROVED** [review]

**Review by zhoney — APPROVED** [review]

**Review by imbajin — APPROVED** [review]
