### PR TITLE
fix: job status is not updated after running

### LINKED ISSUE #112: Job status has not been updated after running
### Steps to reproduce the problem 复现步骤
1. Schedule some(>=4) gremlin jobs which may cost a long time
2. Schedule a gremlin job, we assume the task id is `task-5` and status is `queued`
3. The status of `task-5` won't be updated even if task-5 is running, the status is only changed until it's completed.

hugegraph v0.7.4

### PR DESCRIPTION
**Pull request by javeme**
fix #112

Change-Id: Ic21aaeab25f74a2062206b029079d65deccbee73

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java [hunk 1]
```diff
@@ -211,6 +211,12 @@ public boolean close() {
     }
 
     public <V> HugeTask<V> deleteTask(Id id) {
+        HugeTask<?> task = this.tasks.get(id);
+        if (task != null) {
+            E.checkState(task.completed(),
+                         "Can't delete task '%s' in status %s",
+                         id, task.status());
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java]: call remove(Id) to delete task in memory

Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java]: task in memory would be deleted when task is completed
