### PR TITLE
Fix: config(rest-server.properties) error but HugeGraphServer still up

### LINKED ISSUE #110: 启动HugeGraph提示失败，但线程已经起起来
### Expected behavior 期望表现
{type something here...}
启动HugeGraph server的时候，因为配置错误，提示启动失败，预期是程序没有起起来。 

### Actual behavior 实际表现
{type something here...}
实际上线程已经起起来了。但并没有生成pid file。 
stop脚本，是根据pid file，但这个时候，pid file还没有，所以stop的时候，说线程没起。 stop失败。
后续使用start脚本也会提示端口已经被占用，启动不起来。

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}  0.8.0
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}  centos 7.4
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node} Rocksdb

### PR DESCRIPTION
**Pull request by Linary**
Fix #110

Change-Id: Ib5da6e6c71f2fb6d523b13b75e803b257f0b7035

### CODE REVIEW

File: hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java [hunk 1]
```diff
@@ -41,25 +41,34 @@
...
+        try {
             // Start HugeRestServer
             HugeRestServer.start(args[1]);
         } catch (Exception e) {
-            LOG.error("HugeGraphServer error:", e);
+            LOG.error("HugeRestServer start error: ", e);
             HugeGraph.shutdown(30L);
             throw e;
+        } finally {
+            HugeGremlinServer.stop();
```
Comment (javeme) [inline hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java]: this will be always called even if start successfully

File: hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java [hunk 2]
```diff
@@ -41,25 +41,34 @@
...
-
         if (args.length != 2) {
             String msg = "HugeGraphServer can only accept two config files";
             LOG.error(msg);
             throw new HugeException(msg);
         }
 
+        RegisterUtil.registerBackends();
+        // Scan the jars in plugins directory and load them
+        registerPlugins();
```
Comment (javeme) [inline hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java]: seems we can move method registerPlugins into class RegisterUtil

File: hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGremlinServer.java [hunk 3]
```diff
@@ -33,33 +33,42 @@
...
     private static final String G_PREFIX = "__g_";
 
-    public static void main(String[] args) throws Exception {
+    static {
+        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
+            LOG.info("HugeGremlinServer stopped");
+        }));
+    }
+
+    private static ContextGremlinServer server;
```
Comment (javeme) [inline hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGremlinServer.java]: prefer to let HugeGremlinServer.start() return an instance, same with HugeRestServer.start()

File: hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGremlinServer.java [hunk 4]
```diff
@@ -33,33 +33,42 @@
 
     private static final String G_PREFIX = "__g_";
 
-    public static void main(String[] args) throws Exception {
+    static {
+        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
+            LOG.info("HugeGremlinServer stopped");
+        }));
+    }
```
Comment (javeme) [inline hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGremlinServer.java]: don't need to add so many hooks

File: hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java [hunk 5]
```diff
@@ -41,25 +41,34 @@
...
+
```
Comment (javeme) [inline hugegraph-dist/src/main/java/com/baidu/hugegraph/dist/HugeGraphServer.java]: add `HugeRestServer.register()` and `HugeGremlinServer.register()` to do:
```
RegisterUtil.registerBackends();
RegisterUtil.registerPlugins();
```

just call `HugeRestServer.register()` here
