### PR TITLE
Fix bug: count sql statement leak

### LINKED ISSUE #1626: [Bug] mysql 后端运行一段时间可能内存泄漏
### Bug Type (问题类型)

_No response_

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: mysql nodes, HDD or SSD 
- OS: 8 CPUs, 32 G RAM, Centos 7.x 
- Data Size:  50W vertices, 130W edges 

### 1.参数配置说明：
1. backend后端mysql  实际数据量 顶点数 50W 边数量 130W
2. 有个业务进程会对huge CRUD，大概的读写 每分钟2000左右 大部分是read  
3. jvm配置：
 java -server 
-Dname=HugeGraphServer 
-Dlog4j.configurationFile=/scripts/hugegraph-0.11.2/conf/log4j2.xml 
-Djava.security.manager=com.baidu.hugegraph.security.HugeSecurityManager 
-Xms16g -Xmx16g 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:HeapDumpPath=/scripts/hugegraph-0.11.2/logs 
-XX:+UseGCLogFileRotation 
-XX:GCLogFileSize=10M 
-XX:NumberOfGCLogFiles=3 
-Xloggc:/scripts/hugegraph-0.11.2/logs/gc.log 
-XX:+PrintHeapAtGC 
-XX:+PrintGCDetails 
-XX:+PrintGCDateStamps 
-XX:+UseG1GC 
-XX:MaxGCPauseMillis=1000 
-XX:+ParallelRefProcEnabled 
-XX:InitiatingHeapOccupancyPercent=50 
-XX:G1RSetUpdatingPauseTimePercent=5 
4.顶点边的缓存配置：
hugegraph.properties：开启了l2 堆外
     vertex.cache_type=l2
     vertex.cache_expire=300
     edge.cache_type=l2
     edge.cache_expire=300
### 2.期望表现
1.在发生老年代 GC 时，可以回收掉一部分对象，使得老年代使用量不是持续走高。(实际运行一段时间后高居不下最后FGC，时长高达43s)

### 3.实际情况
gc

jmap统计对象数据：
image
存活对象：
f0abcbe2ba279b0fb74316a9ba99ab0

GC日志：
[gc.log.zip](https://github.com/hugegraph/hugegraph/files/7451158/gc.log.zip)

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by z7658329**
Fix bug: mysql count sql statement leak

fix #1626

### CODE REVIEW

**Comment by z7658329** [comment]
![image](https://user-images.githubusercontent.com/5474723/141063587-99e0ca8d-c4ca-4430-a235-812c27093664.png)

与预期符合每次创建一个新连接，都会close该资源。

监控monitor代码：

image

image

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java [hunk 1]
```diff
@@ -340,6 +340,8 @@ public Number queryNumber(Session session, Query query) {
                 return IteratorUtils.of(rs.resultSet().getLong(1));
             } catch (SQLException e) {
                 throw new BackendException(e);
+            } finally {
+                rs.close();
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java:344]: nice, can you also fix rocksdb:
  ```java
        try (BackendColumnIterator results = this.queryBy(session, query)) {
            if (results instanceof Countable) {
                return ((Countable) results).count();
            }
            return IteratorUtils.count(results);
        }
```

**Review by javeme — COMMENTED** [review]
LGTM!
we can specify the title like `fix resultset leak for count query`

**Review by javeme — APPROVED** [review]

**Review by coderzc — APPROVED** [review]
