### PR TITLE
Fix: batch update edge with edgeId and unmatched sortKeys will create a new edge

### LINKED ISSUE #818: Batch update edge with edgeId and unmatched sortKeys will create a new edge
### Expected behavior 期望表现
Tips: Don't allowed to update edge sortKey values when I specified edgeId

### Actual behavior 实际表现
Created a new edge with passed sortKey values

### PR DESCRIPTION
**Pull request by Linary**
Fix #818

Change-Id: Ic929a4267fc411c156a32e5b381d314f382ebc9a

### CODE REVIEW

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/graph/EdgeAPI.java [hunk 1]
```diff
@@ -402,30 +402,31 @@ public static Direction parseDirection(String direction) {
...
         }
-
-        // TODO: How to get Direction from JsonEdge easily? or any better way?
         EdgeId edgeId = new EdgeId(HugeVertex.getIdValue(newEdge.source),
                                    Directions.OUT, labelId, sortKeys,
                                    HugeVertex.getIdValue(newEdge.target));
+        if (newEdge.id != null) {
+            E.checkArgument(edgeId.equals(newEdge.id),
+                            "The sort key values either be null " +
+                            "or equal with origin");
```
Comment (zhoney) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/api/graph/EdgeAPI.java]: equal to

File: hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java [hunk 2]
```diff
@@ -57,6 +60,82 @@ public void testCreate() throws IOException {
         assertResponseStatus(201, r);
     }
 
+    @Test
+    public void testBatchUpdate() throws IOException {
+        String outVId = getVertexId("person", "name", "marko");
+        String inVId = getVertexId("person", "name", "josh");
+        // create
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java]: Create

File: hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java [hunk 3]
```diff
@@ -57,6 +60,82 @@ public void testCreate() throws IOException {
...
+                + "\"properties\":{"
+                + "\"date\": \"2013-02-20\","
+                + "\"weight\": 1.0}"
+                + "}", outVId, inVId);
+        Response r = client().post(path, edge);
+        // The edge id is 'S1:marko>1>7JooBil0>S1:josh'
+        String content = assertResponseStatus(201, r);
+        String id = parseId(content);
+
+        // update edge with edgeId
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java]: ditto

File: hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java [hunk 4]
```diff
@@ -57,6 +60,82 @@ public void testCreate() throws IOException {
...
+                + "],"
+                + "\"update_strategies\":{"
+                + "\"weight\":\"SUM\","
+                + "\"date\":\"BIGGER\""
+                + "},"
+                + "\"check_vertex\":false,"
+                + "\"create_if_not_exist\":true"
+                + "}", id, outVId, inVId);
+        r = client().put(path + "batch", edge, ImmutableMap.of());
+        // Now allowed to modify sortkey values, the property date has changed
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java]: the property “date” has changed

File: hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java [hunk 5]
```diff
@@ -57,6 +60,82 @@ public void testCreate() throws IOException {
...
+                + "\"update_strategies\":{"
+                + "\"weight\":\"SUM\","
+                + "\"date\":\"BIGGER\""
+                + "},"
+                + "\"check_vertex\":false,"
+                + "\"create_if_not_exist\":true"
+                + "}", outVId, inVId);
+        r = client().put(path + "batch", edge, ImmutableMap.of());
+        // Add a new edge when sortkey value has changed
+        assertResponseStatus(200, r);
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java]: query to assert two different edges

File: hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java [hunk 6]
```diff
@@ -57,6 +60,82 @@ public void testCreate() throws IOException {
...
+                + "\"check_vertex\":false,"
+                + "\"create_if_not_exist\":true"
+                + "}", id, outVId, inVId);
+        r = client().put(path + "batch", edge, ImmutableMap.of());
+        // Now allowed to modify sortkey values, the property date has changed
+        content = assertResponseStatus(400, r);
+        Assert.assertTrue(content.contains(
+                          "either be null or equal with origin"));
+
+        // update edge without edgeId
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/api/EdgeApiTest.java]: Update
