### PR TITLE
Fix query by eq with range index in page only return first page data

### LINKED ISSUE #613: Query by eq with range index in page only return first page data

### PR DESCRIPTION
**Pull request by Linary**
Fix #613

Change-Id: I3cfd3d7ff4ce1ca13b9b6f695ba5ba88569f9266

### CODE REVIEW

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 1]
```diff
@@ -3822,27 +3823,78 @@ public void testQueryByPageWithInvalidLimit() {
...
+        HugeGraph graph = graph();
+        initPageTestData();
+        GraphTraversalSource g = graph.traversal();
+
+        long capacity = 10;
+        long old = Query.defaultCapacity(capacity);
+
+        GraphTraversal<Vertex, Vertex> iter;
+        iter = g.V().has("~page", "").limit(capacity);
+        Assert.assertEquals(10, IteratorUtils.count(iter));
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java]: move into try-catch

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/CoreTestSuite.java [hunk 2]
```diff
@@ -35,16 +35,16 @@
...
-    EdgeCoreTest.class,
-    VertexPropertyCoreTest.class,
-    EdgePropertyCoreTest.class,
-    RestoreCoreTest.class,
-    MultiGraphsTest.class
+//    EdgeCoreTest.class,
+//    VertexPropertyCoreTest.class,
+//    EdgePropertyCoreTest.class,
+//    RestoreCoreTest.class,
+//    MultiGraphsTest.class
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/CoreTestSuite.java]: uncomment

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/EdgeCoreTest.java [hunk 3]
```diff
@@ -2875,23 +2875,15 @@ public void testQueryEdgeByPageWithInvalidLimit() {
 
         HugeGraph graph = graph();
         init100LookEdges();
+        GraphTraversalSource g = graph.traversal();
+        long limit = Query.defaultCapacity() + 1;
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/EdgeCoreTest.java]: long limit => long bigLimit
1 => 1L

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 4]
```diff
@@ -3821,27 +3823,78 @@ public void testQueryByPageWithInvalidLimit() {
...
+
+        HugeGraph graph = graph();
+        GraphTraversalSource g = graph.traversal();
+        initPageTestData();
+
+        long old = Query.defaultCapacity(Query.NO_CAPACITY);
+        try {
+            GraphTraversal<Vertex, Vertex> iter;
+            iter = g.V().has("~page", "").limit(-1);
+            Assert.assertEquals(34, IteratorUtils.count(iter));
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java]: add case limit=20

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 5]
```diff
@@ -3821,27 +3823,78 @@ public void testQueryByPageWithInvalidLimit() {
...
+
+            iter = g.V().has("age", 30).has("~page", "").limit(-1);
+            Assert.assertEquals(18, IteratorUtils.count(iter));
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java]: add case limit=10
