### PR TITLE
fix task scheduler bugs: dead lock and dup server-info

### LINKED ISSUE #1075: server-info-db-worker: Invalid column family specified in write batch
run tinkerpop structure tests:
```
2020-07-02 16:47:46 267883 [server-info-db-worker-1] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:682) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:490) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:295) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:210) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:491) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:345) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.lambda$2(ServerInfoManager.java:209) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1586) ~[rocksdbjni-6.8.1.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:679) ~[classes/:?]
	... 15 more
```

```
2020-07-02 16:47:46 267896 [task-db-worker-1] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:682) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:490) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:295) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:210) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:491) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:345) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.StandardTaskScheduler.lambda$1(StandardTaskScheduler.java:418) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1586) ~[rocksdbjni-6.8.1.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:679) ~[classes/:?]
	... 15 more
```

```
2020-07-02 16:47:46 267833 [task-scheduler-1] [ERROR] com.baidu.hugegraph.task.TaskManager [] - Exception occurred when schedule job
com.baidu.hugegraph.HugeException: Failed to update/query server info: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at com.baidu.hugegraph.task.ServerInfoManager.call(ServerInfoManager.java:272) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.save(ServerInfoManager.java:199) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.heartbeat(ServerInfoManager.java:171) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJob(TaskManager.java:258) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at com.baidu.hugegraph.task.ServerInfoManager.call(ServerInfoManager.java:270) ~[classes/:?]
	... 10 more
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:358) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.lambda$2(ServerInfoManager.java:209) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more
```

### PR DESCRIPTION
**Pull request by javeme**
1. fix dead lock when scheduler-worker hold scheduleTasks lock then
  query tasks, tx() method synchronized(this) wait indefinitely.
2. delete server-info when graph close (when store is initialized)
3. throw exception if task if failed in syncWait (just for debug tinkerpop tests)
4. submit task if there is only single node
5. standardize the status of tasks (add scheduling/scheduled)
6. cancel-task don't remove task from memory if it's single-node server
7. notifyNewTask only notify when the queue is empty(size=1 means one timer task)
8. read/write server-infos in bache duting one scheduling

fix #1075
Change-Id: Icb8d5073f024f0598d439d738d6c0e2caa6fd0cd

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 1]
```diff
@@ -242,17 +237,19 @@ public int pendingTasks() {
     }
 
     protected void notifyNewTask(HugeTask<?> task) {
-        // Notify to schedule tasks initiatively when have new task
-        this.schedulerExecutor.submit(this::scheduleOrExecuteJob);
+        Queue<Runnable> queue = ((ThreadPoolExecutor) this.schedulerExecutor)
+                                                          .getQueue();
+        if (queue.size() <= 1) {
```
Comment (houzhizhen) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:242]: It may schedule more tasks at the same time, and these tasks will not be processed.

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java [hunk 2]
```diff
@@ -248,127 +272,128 @@ private void unlistenChanges() {
...
+    }
+
+    protected ServerInfoManager serverManager() {
+        return this.serverManager;
     }
 
-    protected synchronized <V> void scheduleTasks() {
-        // Master schedule all queued tasks to suitable servers
+    protected synchronized void scheduleTasks() {
+        // Master server schedule all queued tasks to suitable worker servers
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:320]: queued => scheduling

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java [hunk 3]
```diff
@@ -248,127 +272,128 @@ private void unlistenChanges() {
...
                 // Found suitable server, update task server and server load
                 assert server.id() != null;
                 task.server(server.id());
+                task.status(TaskStatus.SCHEDULED);
                 this.save(task);
+
                 server.load(server.load() + task.load());
-                this.serverManager().save(server);
-                LOG.info("Schedule task {} to server {}",
+
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:349]: must save server info here. Otherwise all tasks will be scheduled to same worker

Implement `increaseLoad(int load)` in class `HugeServerInfo`

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java [hunk 4]
```diff
@@ -377,15 +402,14 @@ private void unlistenChanges() {
...
                  */
                 this.initTaskCallable(task);
-                @SuppressWarnings("unchecked")
-                HugeTask<V> memTask = (HugeTask<V>) this.tasks.get(task.id());
+                HugeTask<?> memTask = this.tasks.get(task.id());
                 if (memTask != null) {
                     task = memTask;
                 }
                 Id taskServer = task.server();
                 if (taskServer != null && taskServer.equals(server)) {
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:410]: move to line 397 and change to:

```
Id taskServer = task.server();
assert taskServer != null;
if (!taskServer.equals(server)) {
    continue;
}
```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/ServerInfoManager.java [hunk 5]
```diff
@@ -212,8 +273,8 @@ protected Id save(HugeServerInfo server) {
         });
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/ServerInfoManager.java:273]: remove line 218 due to system tx is auto commit

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java [hunk 6]
```diff
@@ -132,7 +137,14 @@ public int taskResultSizeLimit() {
     private TaskTransaction tx() {
         // NOTE: only the owner thread can access task tx
         if (this.taskTx == null) {
-            synchronized (this) {
+            /*
+             * NOTE: don't synchronized(this) due to scheduler thread hold
+             * this lock through scheduleTasks(), then query tasks and wait
+             * for db-worker thread after call(), the tx may not be initialized
+             * but can't catch this lock, then cause dead lock.
+             * We just use this.eventListener ad a monitor here
```
Comment (Linary) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:145]: as a monitor

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 7]
```diff
@@ -242,17 +237,19 @@ public int pendingTasks() {
     }
 
     protected void notifyNewTask(HugeTask<?> task) {
```
[the remark this answers is not in the document]
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:239]: does not matter, just preserved

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java (hunk 1 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:242]: it's ok to not notify again if there are more than 1 task in queue(like two, one is timer task, one is immediate task), we don't want too many  immediate tasks to be inserted into queue, one notify will cause all the tasks processed.

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java (hunk 3 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:350]: use batch read write

**Comment by javeme** [comment]
image
image

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java [hunk 8]
```diff
@@ -248,65 +271,109 @@ private void unlistenChanges() {
...
+                /*
+                 * Remove task from memory if it's running on worker node,
+                 * but keep task in memory if it's running on master node.
+                 * cancel-scheduling will read task from backend store, if
+                 * removed this instance from memory, there will be two task
+                 * instances with same id, and can't cancel the real task that
+                 * is running but removed from memory.
+                 */
+                this.remove(task);
+            }
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:304]: else means task is on master, cancel it directly seems more efficient

Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/StandardTaskScheduler.java:304]: We assume cancel is not a frequent operation, so it is not optimized
