### PR TITLE
fix ci too much exception "pk table not exist"

### LINKED ISSUE #1075: server-info-db-worker: Invalid column family specified in write batch
run tinkerpop structure tests:
```
2020-07-02 16:47:46 267883 [server-info-db-worker-1] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:682) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:490) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:295) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:210) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:491) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:345) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.lambda$2(ServerInfoManager.java:209) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1586) ~[rocksdbjni-6.8.1.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:679) ~[classes/:?]
	... 15 more
```

```
2020-07-02 16:47:46 267896 [task-db-worker-1] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:682) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:490) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:295) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:210) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:491) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:345) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.StandardTaskScheduler.lambda$1(StandardTaskScheduler.java:418) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1586) ~[rocksdbjni-6.8.1.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:679) ~[classes/:?]
	... 15 more
```

```
2020-07-02 16:47:46 267833 [task-scheduler-1] [ERROR] com.baidu.hugegraph.task.TaskManager [] - Exception occurred when schedule job
com.baidu.hugegraph.HugeException: Failed to update/query server info: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at com.baidu.hugegraph.task.ServerInfoManager.call(ServerInfoManager.java:272) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.save(ServerInfoManager.java:199) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.heartbeat(ServerInfoManager.java:171) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJob(TaskManager.java:258) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at com.baidu.hugegraph.task.ServerInfoManager.call(ServerInfoManager.java:270) ~[classes/:?]
	... 10 more
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:358) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:312) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:573) ~[classes/:?]
	at com.baidu.hugegraph.task.ServerInfoManager.lambda$2(ServerInfoManager.java:209) ~[classes/:?]
	at com.baidu.hugegraph.task.TaskManager$ContextCallable.call(TaskManager.java:308) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more
```

### PR DESCRIPTION
**Pull request by zhoney**
fix #1075
Change-Id: Ie9a1ba689ae4aec876bf9793970a1d62e3c69abf

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java [hunk 1]
```diff
@@ -250,11 +252,13 @@ public void clearBackend() {
         this.loadSystemStore().open(this.configuration);
         this.loadGraphStore().open(this.configuration);
         try {
+            LockUtil.lock(this.name, TaskManager.HEARTBEAT);
             this.storeProvider.clear();
         } finally {
             this.loadGraphStore().close();
             this.loadSystemStore().close();
             this.loadSchemaStore().close();
+            LockUtil.unlock(this.name, TaskManager.HEARTBEAT);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java:261]: move to line 258

File: hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java [hunk 2]
```diff
@@ -268,14 +272,15 @@ public void clearBackend() {
     public void truncateBackend() {
         this.waitUntilAllTasksCompleted();
 
+        LockUtil.lock(this.name, TaskManager.GRAPH_LOCK);
+
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java:276]: remove empty line

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 3]
```diff
@@ -45,7 +45,7 @@
 
     private static final Logger LOG = Log.logger(TaskManager.class);
 
-    public static final String HEARTBEAT = "heartbeat";
+    public static final String GRAPH_LOCK = "graph_lock";
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:48]: move to LockUtil

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 4]
```diff
@@ -276,6 +288,11 @@ private void scheduleOrExecuteJob() {
             }
         } catch (Throwable e) {
             LOG.error("Exception occurred when schedule job", e);
+        } finally {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:291]: only do executeTasksOnWorker and cancelTasksOnWorker when !server.master() or server.onlySingleNode(), and rename server to serverManager

**Comment by zhoney** [comment]
> The following query is triggered each time:
> 
> ```
> 2020-07-18 13:33:26 2589143 [server-info-db-worker-1] [INFO ] com.baidu.hugegraph.backend.Transaction [] - Transaction query: `Query * from VERTEX where id in [server1]`
> 2020-07-18 13:33:26 2589146 [server-info-db-worker-1] [INFO ] com.baidu.hugegraph.backend.Transaction [] - Transaction query: `Query * from VERTEX where [LABEL == -38]`
> 2020-07-18 13:33:26 2589149 [task-db-worker-1] [INFO ] com.baidu.hugegraph.backend.Transaction [] - Transaction query: `Query * from SECONDARY_INDEX page '', limit 2 where [INDEX_LABEL_ID == -54, FIELD_VALUES == 12]`
> 2020-07-18 13:33:26 2589150 [task-db-worker-1] [INFO ] com.baidu.hugegraph.backend.Transaction [] - Transaction query: `Query * from SECONDARY_INDEX page '', limit 2 where [INDEX_LABEL_ID == -54, FIELD_VALUES == 13]`
> 2020-07-18 13:33:26 2589152 [task-db-worker-1] [INFO ] com.baidu.hugegraph.backend.Transaction [] - Transaction query: `Query * from SECONDARY_INDEX page '', limit 2 where [INDEX_LABEL_ID == -54, FIELD_VALUES == 18]`
> ```

this is triggered by `serverStarted()`:
1. first two queries is for server not exist check
2. last three queries is for restoring tasks

**Comment by javeme** [comment]
cassandra:
```
[ERROR] Tests run: 673, Failures: 2, Errors: 1, Skipped: 16, Time elapsed: 495.409 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
[ERROR] testCreateGraphsWithDifferentNameDifferentBackends(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 4.482 s  <<< FAILURE!
java.lang.AssertionError: java.lang.IllegalStateException: Ensure tx closed in all threads when closing graph 'g1'
	at com.baidu.hugegraph.core.MultiGraphsTest.destoryGraphs(MultiGraphsTest.java:344)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphsWithDifferentNameDifferentBackends(MultiGraphsTest.java:299)
[ERROR] testCreateGraphsWithMultiDisksForRocksDB(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 0.797 s  <<< FAILURE!
java.lang.AssertionError: No exception was thrown(expected com.baidu.hugegraph.backend.BackendException)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphsWithMultiDisksForRocksDB(MultiGraphsTest.java:313)
[ERROR] testCreateGraphWithSameNameDifferentBackends(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class com.baidu.hugegraph.HugeFactory]
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
Caused by: java.lang.reflect.InvocationTargetException
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
Caused by: java.lang.IllegalStateException: Graph name 'graph' has been used by backend 'cassandra'
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
```
hbase:
```
[ERROR] Tests run: 673, Failures: 2, Errors: 1, Skipped: 13, Time elapsed: 884.3 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
[ERROR] testCreateGraphsWithDifferentNameDifferentBackends(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 52.635 s  <<< FAILURE!
java.lang.AssertionError: java.lang.IllegalStateException: Ensure tx closed in all threads when closing graph 'g1'
	at com.baidu.hugegraph.core.MultiGraphsTest.destoryGraphs(MultiGraphsTest.java:344)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphsWithDifferentNameDifferentBackends(MultiGraphsTest.java:299)
[ERROR] testCreateGraphsWithMultiDisksForRocksDB(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 0.792 s  <<< FAILURE!
java.lang.AssertionError: No exception was thrown(expected com.baidu.hugegraph.backend.BackendException)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphsWithMultiDisksForRocksDB(MultiGraphsTest.java:313)
[ERROR] testCreateGraphWithSameNameDifferentBackends(com.baidu.hugegraph.core.MultiGraphsTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class com.baidu.hugegraph.HugeFactory]
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
Caused by: java.lang.reflect.InvocationTargetException
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
Caused by: java.lang.IllegalStateException: Graph name 'graph' has been used by backend 'hbase'
	at com.baidu.hugegraph.core.MultiGraphsTest.openGraphWithBackend(MultiGraphsTest.java:365)
	at com.baidu.hugegraph.core.MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends(MultiGraphsTest.java:277)
```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 5]
```diff
@@ -252,30 +254,48 @@ protected void notifyNewTask(HugeTask<?> task) {
...
 
     private void scheduleOrExecuteJob() {
+        List<String> graphs = new ArrayList<>();
         try {
             for (TaskScheduler entry : this.schedulers.values()) {
                 StandardTaskScheduler scheduler = (StandardTaskScheduler) entry;
-                ServerInfoManager server = scheduler.serverManager();
+                ServerInfoManager serverManager = scheduler.serverManager();
+
+                String graph = scheduler.graph().name();
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:263]: add graphName() to call graphparams.name() to avoid auth issue

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java [hunk 6]
```diff
@@ -94,7 +94,7 @@ public void addScheduler(HugeGraphParams graph) {
         this.schedulers.put(graph, scheduler);
     }
 
-    public void closeScheduler(HugeGraphParams graph) {
+    public synchronized void closeScheduler(HugeGraphParams graph) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java:97]: add some comments
