### PR TITLE
fix hbase scan startkey is null NPE

### LINKED ISSUE #1690: [Bug] HBase 表预分区 分区扫描数据发生NPE
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: HBase 2.0.6
- OS: mac
- Data Size:  测试环境

### Expected & Actual behavior (期望与实际表现)

问题复现
image

1. 创建HBase 预分区表
 `create 'hugegraph:g_v','f',SPLITS=>['1000000','2000000','3000000']`
2. 获取点表shards
`http://localhost:8080/graphs/hugegraph/traversers/vertices/shards?split_size=16106127360`

返回结果
`{
    "shards": [
        {
            "start": "MjAwMDAwMA==",
            "end": "MzAwMDAwMA==",
            "length": 0
        },
        {
            "start": "MTAwMDAwMA==",
            "end": "MjAwMDAwMA==",
            "length": 0
        },
        {
            "start": "",
            "end": "MTAwMDAwMA==",
            "length": 0
        },
        {
            "start": "MzAwMDAwMA==",
            "end": "",
            "length": 0
        }
    ]
}`

3. 分片扫描数据
选取start=""的shards 进行请求数据
` {
            "start": "",
            "end": "MTAwMDAwMA==",
            "length": 0
        }`
请求连接
`http://localhost:8080/graphs/hugegraph/traversers/edges/scan?start=&end=MTAwMDAwMA==&page=&page_limit=1`

问题修复：
1. 增加异常堆栈抛出定位问题
2. 处理 null 场景 兼容HBase client Bug 

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by JackyYangPassion**
Fix bug: HBase 表预分区 分区扫描数据发生NPE

fix #1690

### CODE REVIEW

File: hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java [hunk 1]
```diff
@@ -85,7 +85,13 @@ public String writeList(String label, Collection<?> list) {
...
                                  boolean paging) {
         // Early throw if needed
-        iter.hasNext();
+        try{
+            iter.hasNext();
+        }catch (NullPointerException e){
+            e.printStackTrace();
+        }catch (RuntimeException e){
+            e.printStackTrace();
+        }
```
Comment (javeme) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java:94]: IMO, we can't add the catch block and ignore the exception silently.

File: hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java [hunk 2]
```diff
@@ -85,7 +85,13 @@ public String writeList(String label, Collection<?> list) {
     private String writeIterator(String label, Iterator<?> iter,
                                  boolean paging) {
         // Early throw if needed
-        iter.hasNext();
+        try{
+            iter.hasNext();
+        }catch (NullPointerException e){
+            e.printStackTrace();
+        }catch (RuntimeException e){
+            e.printStackTrace();
```
Comment (imbajin) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java:93]: 1. should align/format the code `{}` with space
2. maybe wrapper the exception rather than print stack trace is better
3. shall we ensure iter not null first ?

File: hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java [hunk 3]
```diff
@@ -712,7 +712,11 @@ public RowIterator scan(String table,
                                 byte[] stopRow, boolean inclusiveStop) {
             assert !this.hasChanges();
 
-            Scan scan = new Scan().withStartRow(startRow, inclusiveStart);
+            Scan scan = new Scan();
+            if (startRow != null) {
+                // Bug https://issues.apache.org/jira/browse/HBASE-16498
```
Comment (imbajin) [inline hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java:717]: // Refer: https://issues.apache.org/jira/browse/HBASE-16498 (Bug Fix)

**Comment by imbajin** [comment]
感谢贡献和反馈问题, 欢迎后续 hbase 相关更多的 PR 和设计提交~

File: hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java [hunk 4]
```diff
@@ -712,7 +712,11 @@ public RowIterator scan(String table,
                                 byte[] stopRow, boolean inclusiveStop) {
             assert !this.hasChanges();
 
-            Scan scan = new Scan().withStartRow(startRow, inclusiveStart);
+            Scan scan = new Scan();
+            if (startRow != null) {
```
Comment (javeme) [inline hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java:716]: could you also update `HbaseTable.HbaseShardSpliter.position()`:
```java
        public byte[] position(String position) {
            if (START.equals(position) || END.equals(position)) {
                return null;
            }
            return StringEncoding.decodeBase64(position);
        }
```

**Review by javeme — COMMENTED** [review]
Thank you for your contribution~ some minor comments

File: hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java (hunk 1 above)
Comment (JackyYangPassion) [reply hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java:94]: 增加预分区feature 后 运行hugecomputer 发现 扫描数据发生了NPE，后端hugeserver正常运行，当时通过后端日志以及客户端抛出的NPE 很难定位问题 最后通过DEBUG 跟到代码最外层 通过try{}catch{} 后端输出了异常堆栈 如下：
`java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithoutRetries(RpcRetryingCallerImpl.java:201)
        at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:266)
        at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:434)
        at org.apache.hadoop.hbase.client.ClientScanner.nextWithSyncCache(ClientScanner.java:309)
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:594)
        at org.apache.hadoop.hbase.client.ResultScanner$1.hasNext(ResultScanner.java:53)
        at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$RowIterator.hasNext(HbaseSessions.java:920)
        at com.baidu.hugegraph.backend.serializer.BinaryEntryIterator.fetch(BinaryEntryIterator.java:71)
        at com.baidu.hugegraph.backend.store.BackendEntryIterator.hasNext(BackendEntryIterator.java:59)
        at com.baidu.hugegraph.iterator.ListIterator.<init>(ListIterator.java:37)
        at com.baidu.hugegraph.backend.query.QueryResults.toList(QueryResults.java:173)
        at com.baidu.hugegraph.backend.query.QueryResults.toList(QueryResults.java:91)
        at com.baidu.hugegraph.backend.page.QueryList$OptimizedQuery.iterator(QueryList.java:178)
        at com.baidu.hugegraph.backend.page.QueryList.fetchNext(QueryList.java:121)
        at com.baidu.hugegraph.backend.page.PageEntryIterator.fetch(PageEntryIterator.java:80)
        at com.baidu.hugegraph.backend.page.PageEntryIterator.hasNext(PageEntryIterator.java:66)
        at com.baidu.hugegraph.iterator.FlatMapperIterator.fetch(FlatMapperIterator.java:58)
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40)
        at com.baidu.hugegraph.iterator.FilterIterator.fetch(FilterIterator.java:42)
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40)
        at com.baidu.hugegraph.backend.tx.GraphTransaction$LimitIterator.fetch(GraphTransaction.java:2009)
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40)
        at com.baidu.hugegraph.serializer.JsonSerializer.writeIterator(JsonSerializer.java:93)
        at com.baidu.hugegraph.serializer.JsonSerializer.writeEdges(JsonSerializer.java:224)
        at com.baidu.hugegraph.api.traversers.EdgesAPI.scan(EdgesAPI.java:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)`
增加此段异常捕捉目的是能够快速发现异常原因，目前问题已经定位 此段代码也可以不加 @javeme @imbajin 辛苦帮忙再review下

**Comment by JackyYangPassion** [comment]
> 感谢贡献和反馈问题, 欢迎后续 hbase 相关更多的 PR 和设计提交~

感谢 review ，hbase 和 tidb 相关的会持续贡献

File: hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java (hunk 4 above)
Comment (JackyYangPassion) [reply hugegraph-hbase/src/main/java/com/baidu/hugegraph/backend/store/hbase/HbaseSessions.java:716]: done

File: hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java (hunk 1 above)
Comment (javeme) [reply hugegraph-api/src/main/java/com/baidu/hugegraph/serializer/JsonSerializer.java]: there is an option `exception.allow_trace` to debug issues, we can enable it when needed: https://hugegraph.github.io/hugegraph-doc/config/config-option.html

**Review by javeme — APPROVED** [review]
LGTM

**Review by imbajin — APPROVED** [review]

**Review by zhoney — APPROVED** [review]
