### PR TITLE
fix: gremlin exec timeout cause statement unclose

### LINKED ISSUE #1639: [Bug] gremlin语句执行超时 将导致内存泄漏statement未释放
### Bug Type (问题类型)

_No response_

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.11.x
Backend: mysql nodes, HDD or SSD
OS: 8 CPUs, 32 G RAM, Centos 7.x
Data Size: 50W vertices, 130W edges

### Expected & Actual behavior (期望与实际表现)

1.当一个gremlin语句执行超时后，监控程序记录到该查询并未释放statement
2.gremlin语句为count语句，监控程序记录到该查询并未释放statement

监控monitor代码：
image

image

Expected & Actual behavior (期望与实际表现)

gremlin语法无论执行成功与否都会释放连接

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by z7658329**
Fix bug: gremlin语句执行超时 将导致内存泄漏statement未释放

fix #1639

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java [hunk 1]
```diff
@@ -115,8 +118,17 @@ protected final boolean reachLimit() {
     }
 
     protected final boolean reachLimit(long count) {
-        checkInterrupted();
-        return this.query.reachLimit(count);
+        try {
+            checkInterrupted();
+            return this.query.reachLimit(count);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java:123]: it's ok to just catch `checkInterrupted()`, we assume other exception will be handled by upper layer.

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java [hunk 2]
```diff
@@ -115,8 +118,17 @@ protected final boolean reachLimit() {
...
+        } catch (BackendException e) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java:124]: catch Throwable

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java [hunk 3]
```diff
@@ -115,8 +118,17 @@ protected final boolean reachLimit() {
...
+            try {
+                this.close();
+            } catch (Exception ex) {
+                LOG.warn("Failed to close backend entry iterator for interrupted query", ex);
+            }
+            throw e;
+        }
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java:131]: also catch `QueryResults.toList(Iterator<T> iterator)` which may cause leak if exception occurred, and close in finally block:
```java
try {
    return new ListIterator<>(Query.DEFAULT_CAPACITY, iterator);
} finally {
    CloseableIterator.closeIterator(iterator);
}
```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java [hunk 4]
```diff
@@ -115,7 +118,16 @@ protected final boolean reachLimit() {
     }
 
     protected final boolean reachLimit(long count) {
-        checkInterrupted();
+        try {
+            checkInterrupted();
+        } catch (Throwable e) {
+            try {
+                this.close();
+            } catch (Exception ex) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java:126]: `catch(Throwable ex)`

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java [hunk 5]
```diff
@@ -115,7 +118,16 @@ protected final boolean reachLimit() {
     }
 
     protected final boolean reachLimit(long count) {
-        checkInterrupted();
+        try {
+            checkInterrupted();
+        } catch (Throwable e) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/BackendEntryIterator.java:123]: don't need a space between "catch ("

**Review by javeme — APPROVED** [review]

**Review by imbajin — APPROVED** [review]

**Review by zhoney — APPROVED** [review]
