### PR TITLE
fix(core): edge cache not clear when update or delete associated vertex

### LINKED ISSUE #1779: [Bug] edge-cache-clear should account for vertex update
### Bug Type (问题类型)

logic (逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0

### Expected & Actual behavior (期望与实际表现)

edge-cache-clear should account for vertex update operations, since adjacency vertex lookups are affected by old adjacency vertex properties.

Consider adjusting to the following logic:
`boolean invalidEdgesCache = this.edgesInTxSize() + updates.size() + Deletes.size() > 0;`
https://github.com/hugegraph/hugegraph/blob/72baa123b135240476718f735c085577b761a970/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/CachedGraphTransaction.java#L367

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by sunlujing**
1. fix the bug when vertex updated, but the edge cache associated with that vertex was not updated. Here we simply clear all edge cache when  any vertex changes.
2. add two test case for the fixing

fix #1779

### CODE REVIEW

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java [hunk 1]
```diff
@@ -65,14 +67,27 @@ private CachedGraphTransaction cache() {
...
+        graph.schema().propertyKey("name").asText()
+                .checkExist(false).create();
         graph.schema().vertexLabel("person")
-                      .idStrategy(IdStrategy.CUSTOMIZE_NUMBER)
-                      .checkExist(false)
-                      .create();
+                .idStrategy(IdStrategy.CUSTOMIZE_NUMBER)
+                .properties("name").nullableKeys("name")
+                .checkExist(false)
+                .create();
```
Comment (imbajin) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java:76]: we could keep original format. so as other lines (align lines)

**Review by imbajin — COMMENTED** [review]
Thanks for your contribution, a little comments for it.

For code style problems, prefer to use our [config](https://github.com/hugegraph/hugegraph/blob/master/hugegraph-style.xml) (if u use IDEA)

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java [hunk 2]
```diff
@@ -125,4 +140,87 @@ public void testEventInvalid() throws Exception {
...
+        Assert.assertEquals(0L,
+                Whitebox.invoke(cache, "edgesCache", "size"));
+        String name = cache.queryEdgesByVertex(IdGenerator.of(1)).next().outVertex()
+                .value("name");
+        Assert.assertEquals("test-name",name);
+
+
+    }
 }
+
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java:226]: can remove useless line

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java [hunk 3]
```diff
@@ -125,4 +140,87 @@ public void testEventInvalid() throws Exception {
...
+                cache.graph().schema().getPropertyKey("name"),"test-name"));
+        cache.commit();
+
+        Assert.assertEquals(0L,
+                Whitebox.invoke(cache, "edgesCache", "size"));
+        String name = cache.queryEdgesByVertex(IdGenerator.of(1)).next().outVertex()
+                .value("name");
+        Assert.assertEquals("test-name",name);
+
+
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java:223]: can remove useless line

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java [hunk 4]
```diff
@@ -125,4 +140,87 @@ public void testEventInvalid() throws Exception {
...
+        cache.commit();
+
+        Assert.assertEquals(0L,
+                Whitebox.invoke(cache, "edgesCache", "size"));
+        Assert.assertFalse(cache.queryEdgesByVertex(IdGenerator.of(2)).hasNext());
+
+    }
+
+    @Test
+    public void testClearEdgeCacheWhenUpdateVertex(){
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java:183]: Thanks for contributing test cases

**Review by javeme — COMMENTED** [review]
Thanks for your contribution! The code logic looks good, can we adjust the code style?
You can refer to the code style guide: https://github.com/hugegraph/hugegraph-doc/wiki/HugeGraph%E4%BB%A3%E7%A0%81%E9%A3%8E%E6%A0%BC%E6%8C%87%E5%8D%97

**Comment by sunlujing** [comment]
have reformated code style

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/CachedGraphTransaction.java [hunk 5]
```diff
@@ -394,8 +394,13 @@ protected final void commitMutation2Backend(BackendMutation... mutations) {
                 }
             }
 
-            // Update edge cache if any edges change
-            if (edgesInTxSize > 0 && this.enableCacheEdge()) {
+            /*
+             * Update edge cache if any vertex or edge changed
+             * For vertex change, the edges linked with should also be updated
+             * Before we use a more precise strategy,now we just clear all the edge cache
```
Comment (imbajin) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/CachedGraphTransaction.java:400]: enhance to--> Before we find a more precise strategy, just clear all the edge cache now (expect a space after `,`)

**Review by imbajin — APPROVED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/CachedGraphTransaction.java (hunk 5 above)
Comment (sunlujing) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/cache/CachedGraphTransaction.java]: done

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java [hunk 6]
```diff
@@ -125,4 +140,84 @@ public void testEventInvalid() throws Exception {
         Assert.assertEquals(2L,
                             Whitebox.invoke(cache, "verticesCache", "size"));
     }
+
+
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java:144]: one blank line is ok

**Review by javeme — DISMISSED** [review]

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java (hunk 6 above)
Comment (sunlujing) [reply hugegraph-test/src/main/java/com/baidu/hugegraph/unit/cache/CachedGraphTransactionTest.java]: done

**Comment by sunlujing** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sunlujing** [comment]
recheck

**Review by imbajin — APPROVED** [review]
