### PR TITLE
fix(core): traversal contains Tree step has different result in v0.12

### LINKED ISSUE #1745: 从0.11.2升级到0.12.0版本，同样的gremlin语句执行返回的结果不一样，有没有相关的迁移注意事项或指引
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  少于1000vertices, 少于1000 edges 

### Expected & Actual behavior (期望与实际表现)

```groovy
g.V().hasLabel('cmdb_model_group').has('cmdb_parent_id', '-1')
  .repeat(__.out('cmdb_parent').has('tenant_id', 'operate'))
  .until(__.outE('cmdb_parent').count().is(0)).tree()
```

同样的gremlin语句，在0.11.2版本中执行返回的数据和在0.12.0版本中执行返回的数据不一样。
数据库的数据是一样的。
期望：执行结果一样
实际：执行结果不一样

[result.zip](https://github.com/hugegraph/hugegraph/files/7965322/result.zip)

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by vincentshu**
…result comparing with [version 0.11.2]

fix #1745

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepStrategy.java [hunk 1]
```diff
@@ -98,6 +100,24 @@ protected static boolean containsPath(Traversal.Admin<?, ?> traversal) {
...
     }
 
+    /**
+     * Does a Traversal contain any Tree step
+     * @param traversal
+     * @return the traversal or its parents contain at least one Tree step
+     */
+    protected static boolean containsTree(Traversal.Admin<?, ?> traversal) {
+        boolean hasPath = TraversalHelper.getStepsOfClass(
+                TreeStep.class, traversal).size() > 0;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepStrategy.java:110]: prefer to align with TraversalHelper

File: hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepStrategy.java [hunk 2]
```diff
@@ -98,6 +100,24 @@ protected static boolean containsPath(Traversal.Admin<?, ?> traversal) {
         return containsPath(parent.asStep().getTraversal());
     }
 
+    /**
+     * Does a Traversal contain any Tree step
+     * @param traversal
+     * @return the traversal or its parents contain at least one Tree step
+     */
+    protected static boolean containsTree(Traversal.Admin<?, ?> traversal) {
+        boolean hasPath = TraversalHelper.getStepsOfClass(
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepStrategy.java:109]: can we rename hasPath to hasTree?

**Review by javeme — COMMENTED** [review]
Thanks for your contribution! some minor comments~

**Review by javeme — APPROVED** [review]

**Review by imbajin — APPROVED** [review]

**Review by coderzc — APPROVED** [review]
