### PR TITLE
unify special chars in index property

### LINKED ISSUE #1638: Exception while inserting special char values like '\\u0000'
### Problem Type (问题类型)

Exception while inserting special chars

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

When i try to push the constant value '\\u0000' through JAVA API ,it results in java.lang.IllegalArgumentException.How to insert these type of values in hugegraph?

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
[
  {
    "label": "CONSTANT",
    "id": 1,
    "properties": {
      "VALUE": "\u0000",
      "CLASS_NAME": "Ljava/lang/String;"
    }
  }
]
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by javeme**
just not allow leading special char in index property,
it's ok a special char is placed in non-leading position.

NOTE: not allowed 0x00 byte in any position for pgsql/rocksdb/hbase

fix #1638

Change-Id: Id3f0eb39c30da2ff4b11221df0e138cc77c885b2

### CODE REVIEW

**Review by coderzc — APPROVED** [review]

**Comment by javeme** [comment]
ci error of postgresql:
```
testAddVertexPropertyWithSpecialValueForSecondaryIndex(com.baidu.hugegraph.core.VertexCoreTest)  Time elapsed: 0.455 s  <<< ERROR!
com.baidu.hugegraph.backend.BackendException: Failed to commit
	at com.baidu.hugegraph.core.VertexCoreTest.testAddVertexPropertyWithSpecialValueForSecondaryIndex(VertexCoreTest.java:6004)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO g_si (FIELD_VALUES, EXPIRED_TIME, ELEMENT_IDS, INDEX_LABEL_ID) VALUES ('aa', 0, 'S764:0', 199) ON CONFLICT (FIELD_VALUES, INDEX_LABEL_ID, ELEMENT_IDS) DO UPDATE SET FIELD_VALUES = 'aa', EXPIRED_TIME = 0, ELEMENT_IDS = 'S764:0', INDEX_LABEL_ID = 199 was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00  Call getNextException to see other errors in the batch.
	at com.baidu.hugegraph.core.VertexCoreTest.testAddVertexPropertyWithSpecialValueForSecondaryIndex(VertexCoreTest.java:6004)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
	at com.baidu.hugegraph.core.VertexCoreTest.testAddVertexPropertyWithSpecialValueForSecondaryIndex(VertexCoreTest.java:6004)
```

**Review by coderzc — APPROVED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 1]
```diff
@@ -1350,22 +1338,22 @@ private static ConditionQuery constructQuery(ConditionQuery query,
         String joinedValues;
         // 2.1 All fields have equal-conditions
         if (prefixes.size() == fields.size()) {
-            // Prefix numeric values should be converted to sortable string
+            // Prefix numeric values should be converted to sort-able string
```
Comment (imbajin) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1341]: why change this word?

**Review by imbajin — DISMISSED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java (hunk 1 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1341]: The IDE prompt "The word 'sortable' is not correctly spelled",  I will revert to "sortable".

**Review by imbajin — APPROVED** [review]

**Review by coderzc — APPROVED** [review]
