### PR TITLE
refact(core): support Infinity & NaN number in float/double property

### LINKED ISSUE #1575: [Bug] HugeGraph could not process Inifnity/NaN value in float/double
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Memory 
- OS: 10 CPUs, 125 G RAM, Centos 7.x 
- Data Size:  100 vertices, 200 edges 

### Expected & Actual behavior (期望与实际表现)

**Expected Behavior**
We expected to write `Double.Infinity` value into HugeGraph. 

**Current Behavior**

An exception was thrown.
```
class java.lang.IllegalArgumentException: Invalid property value 'Infinity' for key 'price', expect a value of type Double, actual type String
at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:178)
at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:58)
at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:96)
```

**Steps to Reproduce**
```
hugegraph.schema().propertyKey("name").asText().ifNotExist().create();
hugegraph.schema().propertyKey("price").asDouble().ifNotExist().create();

// vertex
hugegraph.schema().vertexLabel("person").properties("name").nullableKeys("name").create();
hugegraph.schema().indexLabel("personbyname").onV("person").by("name").shard().ifNotExist().create();
hugegraph.schema().vertexLabel("product").properties("name","price").nullableKeys("name","price").create();
hugegraph.schema().indexLabel("productbyname").onV("product").by("name").shard().ifNotExist().create();
hugegraph.schema().indexLabel("productbyprice").onV("product").by("price").shard().ifNotExist().create();

GraphManager graph = hugegraph.graph();

/** create graph data */
Vertex nancy = new Vertex("person").property("name", "nancy");
Vertex product1 = new Vertex("product").property("name", "product1").property("price", 3.254615);
Vertex product2 = new Vertex("product").property("name", "product2").property("price", new Double(1029.98 / 0));

graph.addVertices(Arrays.asList(nancy, product1, product2));
```

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by imbajin**
Fix #1575 :
1. due to this, float can support the value > Float.MAX (treat as Infinity), so as the double
2. add test case in client (later)

PS: Shall we delete old test cases directly

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java [hunk 1]
```diff
@@ -104,15 +107,22 @@ public boolean isUUID() {
         return this == DataType.UUID;
     }
 
+    private <V> boolean isInfinityOrNaN(V value) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java:110]: set static

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/PropertyCoreTest.java [hunk 2]
```diff
@@ -462,13 +467,13 @@ public void testTypeFloat() {
                                              1f, 3f, 3f, 127f, 128f));
 
         Assert.assertThrows(IllegalArgumentException.class, () -> {
-            property("float", Double.MAX_VALUE);
+            property("float", 'a');
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/PropertyCoreTest.java:470]: what's the behavior of property("float", Double.MAX_VALUE)? can also test it

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 3]
```diff
@@ -283,18 +283,18 @@ public void testAddVertexWithInvalidPropertValueOfFloat() {
...
+        //    graph.addVertex(T.label, "number", "float", value);
+        //});
+        //Assert.assertThrows(IllegalArgumentException.class, () -> {
+        //    double value = -(Float.MAX_VALUE * 2.0d);
+        //    graph.addVertex(T.label, "number", "float", value);
+        //});
+        //
+        //Assert.assertThrows(IllegalArgumentException.class, () -> {
+        //    graph.addVertex(T.label, "number", "float", Double.MAX_VALUE);
+        //});
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:297]: ditto

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 4]
```diff
@@ -318,16 +318,16 @@ public void testAddVertexWithInvalidPropertValueOfDouble() {
...
+        //Assert.assertThrows(IllegalArgumentException.class, () -> {
+        //    BigDecimal two = new BigDecimal(2);
+        //    BigDecimal value = new BigDecimal(Double.MAX_VALUE).multiply(two);
+        //    graph.addVertex(T.label, "number", "double", value);
+        //});
+        //Assert.assertThrows(IllegalArgumentException.class, () -> {
+        //    BigDecimal two = new BigDecimal(2);
+        //    BigDecimal value = new BigDecimal(-Double.MAX_VALUE).multiply(two);
+        //    graph.addVertex(T.label, "number", "double", value);
+        //});
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:330]: ditto

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/PropertyCoreTest.java (hunk 2 above)
Comment (imbajin) [reply hugegraph-test/src/main/java/com/baidu/hugegraph/core/PropertyCoreTest.java:470]: treat as `Infinity`. add a assertEquals for it

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java (hunk 3 above)
Comment (imbajin) [reply hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:297]: this method only tests `InvalidProperty`, test & move to `PropertyCoreTest`,

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java (hunk 4 above)
Comment (imbajin) [reply hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:330]: ditto, move to `PropertyCoreTest`

**Review by javeme — DISMISSED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java [hunk 5]
```diff
@@ -49,6 +49,9 @@
     private final byte code;
     private final String name;
     private final Class<?> clazz;
+    private final static String POSITIVE_INFINITY = "Infinity";
+    private final static String NEGATIVE_INFINITY = "-Infinity";
+    private final static String NaN = "NaN";
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java:54]: use ImmutableSet and contains()?

Comment (imbajin) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java:54]: seems no benefit if we don't have method like `CollectionUtils.containsAny()`?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java [hunk 6]
```diff
@@ -108,9 +108,7 @@ public boolean isUUID() {
     }
 
     private static <V> boolean isInfinityOrNaN(V value) {
-        return value instanceof String &&
-               (POSITIVE_INFINITY.equals(value) ||
-                NEGATIVE_INFINITY.equals(value) || NaN.equals(value));
+        return value instanceof String && specialNums.contains(value);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java:111]: prefer to move isInfinityOrNaN() to JsonUtil

File: hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java [hunk 7]
```diff
@@ -49,9 +50,11 @@
     private final byte code;
     private final String name;
     private final Class<?> clazz;
+    private final static ImmutableSet<String> specialNums;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/DataType.java:53]: Set<String> specialFloats

**Review by zhoney — APPROVED** [review]
