### PR TITLE
Fix left range index

### LINKED ISSUE #1495: [Bug] range index 残留索引导致统计不准确
## How to reproduce ( 复现步骤 )

当前vertex写入相同id数据时，老索引并不会删除，会在后续查询是通过condtion条件过滤进行删除

但是range索引会存在问题，例如我们写入2000条数据

```java

        SchemaManager schema = graph.schema();

        schema.vertexLabel("sj").properties("name", "update_time")
              .primaryKeys("name").create();

        schema.indexLabel("sj_update_time_range").onV("sj").range()
              .by("update_time").create();

        for (int i=1; i<=2000; i++) {
            graph.addVertex(T.label, "sj", "name", "sj"+i,
                            "update_time", i);
        }
        graph.tx().commit();

        List<Vertex> vertices;
        long count = graph.traversal().V().has("sj", "update_time", ConditionP.gt(0))
                                          .count().next();
        Assert.assertEquals(2000L, count);
```

让后更新 `update_time`：

```java
        for (int i=1; i<=2000; i++) {
            graph.addVertex(T.label, "sj", "name", "sj"+i,
                            "update_time", 2*i);
        }
        graph.tx().commit();

        count = graph.traversal().V().has("sj", "update_time", ConditionP.gt(0))
                                     .count().next();
        Assert.assertEquals(2000L, count);
```

查询结果是3500：

```java
Exception in thread "main" java.lang.AssertionError: expected:<2000> but was:<3500>
 at org.junit.Assert.fail(Assert.java:88)
```

### PR DESCRIPTION
**Pull request by jadepeng**
fixed #1495

### CODE REVIEW

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 1]
```diff
@@ -408,6 +409,48 @@ public void testAddVertexWithInvalidPropertyList() {
...
     }
 
+    @Test
+    public void testRemoveLeftRangeIndex(){
+        HugeGraph graph = graph();
+        SchemaManager schema = graph.schema();
+
+        schema.propertyKey("update_time").asLong().create();
+
+        schema.vertexLabel("sj").properties("name", "update_time")
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:419]: improve "sj"

File: hugegraph-core/src/main/java/com/baidu/hugegraph/config/CoreOptions.java [hunk 2]
```diff
@@ -352,6 +352,14 @@ public static synchronized CoreOptions instance() {
                     false
             );
 
+    public static final ConfigOption<Boolean> VERTEX_REMOVE_LEFT_INDEX =
+            new ConfigOption<>(
+                    "vertex.remove_left_index",
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/config/CoreOptions.java:357]: remove_left_index_at_overwrite

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 3]
```diff
@@ -1628,6 +1665,17 @@ private boolean rightResultFromIndexQuery(Query query, HugeElement elem) {
 
         ConditionQuery cq = (ConditionQuery) query;
         if (cq.optimized() == OptimizedType.NONE || cq.test(elem)) {
+            ConditionQuery.IndexLeft index =
+                    cq.getIndexLeft(elem.id());
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:1669]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 4]
```diff
@@ -352,6 +359,36 @@ protected void prepareAdditions(Map<Id, HugeVertex> addedVertices,
...
+                            "The newly added vertex with id:'%s' label:'%s' " +
+                            "is not allowed to insert, because already exist " +
+                            "a vertex with same id and different label:'%s'",
+                            newVertex.id(), newVertex.label(),
+                            existedVertex.label());
+                }
+                this.indexTx.updateVertexIndex(existedVertex, true);
+            }
+        }
+        finally {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:387]: move to previous line

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 5]
```diff
@@ -149,6 +149,8 @@ public GraphTransaction(HugeGraphParams graph, BackendStore store) {
              conf.get(CoreOptions.VERTEX_ADJACENT_VERTEX_EXIST);
         this.lazyLoadAdjacentVertex =
              conf.get(CoreOptions.VERTEX_ADJACENT_VERTEX_LAZY);
+        this.removeLeftIndexOnSave =
+                conf.get(CoreOptions.VERTEX_REMOVE_LEFT_INDEX);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:153]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 6]
```diff
@@ -1589,62 +1629,49 @@ protected long removeIndexLeft(ConditionQuery query,
...
+                IndexLabel indexLabel = findMatchedIndexLabel(query);
+                assert indexLabel != null;
+
+                AbstractSerializer serializer = tx.serializer;
+                for (Object value : values) {
+                    HugeIndex index = new HugeIndex(this.graph(), indexLabel);
+                    index.elementIds(element.id());
+                    index.fieldValues(value);
+                    tx.doEliminate(serializer.writeIndex(index));
+                    tx.commit();
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1656]: can commit by batch

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 7]
```diff
@@ -1538,13 +1576,15 @@ private static Query parent(Collection<Query> queries) {
         private final ConditionQuery query;
         private final HugeElement element;
         private GraphIndexTransaction tx;
+        private ConditionQuery.IndexLeft leftIndex;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1579]: keep class name and var name the same like LeftIndex

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 8]
```diff
@@ -1589,62 +1629,49 @@ protected long removeIndexLeft(ConditionQuery query,
             for (ConditionQuery cq: ConditionQueryFlatten.flatten(query)) {
                 // Process range index
                 rCount += this.processRangeIndexLeft(cq, element);
-                // Process secondary index or search index
-                sCount += this.processSecondaryOrSearchIndexLeft(cq, element);
+                if (this.leftIndex == null) {
+                    // Process secondary index or search index
+                    sCount +=
+                            this.processSecondaryOrSearchIndexLeft(cq, element);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1635]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 9]
```diff
@@ -1589,62 +1629,49 @@ protected long removeIndexLeft(ConditionQuery query,
             for (ConditionQuery cq: ConditionQueryFlatten.flatten(query)) {
                 // Process range index
                 rCount += this.processRangeIndexLeft(cq, element);
-                // Process secondary index or search index
-                sCount += this.processSecondaryOrSearchIndexLeft(cq, element);
+                if (this.leftIndex == null) {
+                    // Process secondary index or search index
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1633]: may the leftIndex be non-null if it's secondary index or search index?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 10]
```diff
@@ -621,6 +623,41 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
         });
     }
 
+    private void cacheIndexValues(ConditionQuery query, HugeIndex index) {
+        if (query.originQuery() instanceof ConditionQuery) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:627]: also move to shouldCacheIndexValue

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 11]
```diff
@@ -621,6 +623,41 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
+            if (shouldCacheIndexValue(index)) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:628]: return if (!shouldCacheIndexValue(index));

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 12]
```diff
@@ -621,6 +623,41 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
+                for (Id id : index.elementIds()) {
+                    Id fieldId = index.indexLabel().indexField();
+                    ConditionQuery originQuery =
+                                   ((ConditionQuery) query.originQuery());
+                    Map<Id, Object> valueMap =
+                                    originQuery.getMatchedIndexValues(fieldId);
+                    Object indexValue = index.fieldValues();
+                    if (valueMap.containsKey(id)) {
+                        /*
+                         * If there are more than one index , cache the values
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:638]: keep unify struct, prefer to define a class

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 13]
```diff
@@ -603,14 +611,42 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX_FILTER
     }
 
-    public static class IndexLeft {
-        Object value;
-        Id property;
+    public static class CachedIndexValues {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:614]: seems not a cache, can rename to Element2IndexValueMap

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 14]
```diff
@@ -623,39 +622,43 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
-                        } else {
-                            valueMap.put(id,
-                                         Sets.newHashSet(value, indexValue));
-                        }
-                    } else {
-                        valueMap.put(id, index.fieldValues());
-                    }
-                }
-            }
+    private void cacheIndexValues(ConditionQuery query, HugeIndex index,
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:625]: rename to recordIndexValue

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 15]
```diff
@@ -623,39 +622,43 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
+        Id fieldId = index.indexLabel().indexField();
+        for (Id id : index.elementIds()) {
+            Object value = fixValueDataType(index.fieldValues(), indexLabel);
+            originQuery.cachedIndexValues(fieldId)
+                       .addCache(id, value);
         }
     }
 
-    private boolean shouldCacheIndexValue(HugeIndex index) {
+    private Object fixValueDataType(Object value, IndexLabel indexLabel) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:641]: move this method to IndexLabel class, and rename to validValue(Object value)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 16]
```diff
@@ -623,39 +622,43 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
+        Number number = (Number)value;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:642]: just return and don't convert to Number if not range index

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 17]
```diff
@@ -611,34 +609,25 @@ private static Object convertNumberIfNeeded(Object value) {
...
             } else {
-                elementIndexValues.put(id, indexValue);
+                element2IndexValues.put(id, Sets.newHashSet(indexValue));
             }
         }
 
-        public Object getCachedIndexValues(Id elementId){
-            return elementIndexValues.get(elementId);
+        public Set<Object> getIndexValues(Id elementId){
+            return element2IndexValues.get(elementId);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:630]: add prefix "this.element2IndexValues"

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 18]
```diff
@@ -611,34 +609,25 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX_FILTER
     }
 
-    public static class CachedIndexValues {
+    public static class Element2IndexValueMap {
         Id propertyId;
-        Map<Id, Object> elementIndexValues;
+        Map<Id, Set<Object>> element2IndexValues;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:614]: set final

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 19]
```diff
@@ -611,34 +609,25 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX_FILTER
     }
 
-    public static class CachedIndexValues {
+    public static class Element2IndexValueMap {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:612]: add empty line after class define

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 20]
```diff
@@ -455,52 +455,50 @@ public LeftIndex getLeftIndex(Id elementId) {
...
+            return true;
         }
 
         Condition.UserpropRelation propRelation =
                                    (Condition.UserpropRelation)cond;
         Id propId = propRelation.key();
-        Object value = this.cachedIndexValues
-                           .getCachedIndexValues(element.id());
+        Set<Object> value = this.element2IndexValueMap
+                           .getIndexValues(element.id());
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:470]: align with .element2IndexValueMap

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 21]
```diff
@@ -455,52 +455,50 @@ public LeftIndex getLeftIndex(Id elementId) {
...
+            element2IndexValueMap == null) {
+            return true;
         }
 
         Condition.UserpropRelation propRelation =
                                    (Condition.UserpropRelation)cond;
         Id propId = propRelation.key();
-        Object value = this.cachedIndexValues
-                           .getCachedIndexValues(element.id());
+        Set<Object> value = this.element2IndexValueMap
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:469]: rename to values

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 22]
```diff
@@ -444,7 +444,7 @@ public boolean test(HugeElement element) {
                 return false;
             }
 
-            if (hasErrorMatchedRangeIndex(element, cond)) {
+            if (!validRangeIndex(element, cond)) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:447]: is there the same issue with search index and union index?
can remove the empty line

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 23]
```diff
@@ -455,52 +455,50 @@ public LeftIndex getLeftIndex(Id elementId) {
...
         }
-
-        return false;
+        return hasRightValue;
     }
 
     private boolean numberEquals(Object number1, Object number2) {
-        // eg. number1 is int 1 ,number 2 is long 1
+        // Same class compare directly
+        if (number1.getClass().equals(number2.getClass())) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:497]: nice improvement

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 22 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:447]: 我的理解search index在搜索的时候有过滤，应该还好
union index 需要验证下

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 24]
```diff
@@ -621,6 +622,28 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
...
     }
 
+    private void recordIndexValue(ConditionQuery query, HugeIndex index,
+                                  IndexLabel indexLabel) {
+        if (!shouldRecordIndexValue(query, index)) {
+            return;
+        }
+
+        ConditionQuery originQuery =
+                ((ConditionQuery) query.originQuery());
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:632]: align with originQuery

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 25]
```diff
@@ -149,6 +149,8 @@ public GraphTransaction(HugeGraphParams graph, BackendStore store) {
              conf.get(CoreOptions.VERTEX_ADJACENT_VERTEX_EXIST);
         this.lazyLoadAdjacentVertex =
              conf.get(CoreOptions.VERTEX_ADJACENT_VERTEX_LAZY);
+        this.removeLeftIndexOnSave =
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:152]: removeLeftIndexOnOverwrite

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 26]
```diff
@@ -352,6 +359,35 @@ protected void prepareAdditions(Map<Id, HugeVertex> addedVertices,
...
+        }
+        IdQuery idQuery = new IdQuery(HugeType.VERTEX, ids);
+        Iterator<HugeVertex> results = this.queryVerticesFromBackend(idQuery);
+        try {
+            while (results.hasNext()) {
+                HugeVertex existedVertex = results.next();
+                HugeVertex newVertex = vertices.get(existedVertex.id());
+                if (!existedVertex.label().equals(newVertex.label())) {
+                    throw new HugeException(
+                            "The newly added vertex with id:'%s' label:'%s' " +
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:378]: align with new

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 27]
```diff
@@ -522,4 +607,54 @@ private static Object convertNumberIfNeeded(Object value) {
...
+            this.value = value;
+            this.property = property;
+        }
+
+        public Object value() {
+            return value;
+        }
+
+        public void value(Object value) {
+            this.value = value;
```
[the remark this answers is not in the document]
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:649]: 暂时不需要

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 28]
```diff
@@ -51,6 +54,8 @@
 
     private OptimizedType optimizedType = OptimizedType.NONE;
     private Function<HugeElement, Boolean> resultsFilter = null;
+    private Element2IndexValueMap element2IndexValueMap = null;
+    private Map<Id, LeftIndex> leftIndexMap = new HashMap<>();
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:58]: set null by default

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 22 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:446]: union index 看起来是需要解决这个问题的。

Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:446]: this.validRangeIndex()

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 29]
```diff
@@ -522,4 +607,54 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX,
         INDEX_FILTER
     }
+
+    public static class Element2IndexValueMap {
+
+        Id propertyId;
```
[the remark this answers is not in the document]
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:613]: set private final

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 30]
```diff
@@ -522,4 +607,46 @@ private static Object convertNumberIfNeeded(Object value) {
...
+        final Map<Id, Set<Object>> element2IndexValues;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:614]: set private final

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 28 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:58]: can we move Map<Id, LeftIndex> leftIndexMap to Element2IndexValueMap?

**Comment by javeme** [comment]
there are too many logs like:
```
2021-06-25 02:51:10 [main] [INFO] c.b.h.b.Transaction - Remove left index: v[678:soft1], query: `Query * from VERTEX where [LABEL == 678, 1852 > 0]`

```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 22 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java]: > union index 看起来是需要解决这个问题的。

验证，union index 可以正确过滤，见新增的测试用例

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 31]
```diff
@@ -443,81 +447,17 @@ public boolean test(HugeElement element) {
             if (!cond.test(element)) {
                 return false;
             }
-            if (!validRangeIndex(element, cond)) {
+
+            if (this.element2IndexValueMap == null) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:451]: merge to line 454 with `this.element2IndexValueMap != null`

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 32]
```diff
@@ -608,14 +548,16 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX_FILTER
     }
 
-    public static class Element2IndexValueMap {
+    public static final class Element2IndexValueMap {
 
-        Id propertyId;
-        final Map<Id, Set<Object>> element2IndexValues;
+        private Id propertyId;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:553]: set final

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 33]
```diff
@@ -629,6 +571,74 @@ public void addValue(Id id, Object indexValue) {
...
+             * waiting to be removed
+             */
+            boolean hasRightValue = removeValue(values, hugeProperty.value());
+            if (values.size() > 0) {
+                addLeftIndex(propId, values, element.id());
+            }
+            return hasRightValue;
+        }
+
+        private boolean numberEquals(Object number1, Object number2) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:619]: set static and move to line 641

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 34]
```diff
@@ -629,6 +571,74 @@ public void addValue(Id id, Object indexValue) {
...
+                                        Condition cond) {
+            // Not UserpropRelation
+            if (!(cond instanceof Condition.UserpropRelation)) {
+                return true;
+            }
+
+            Condition.UserpropRelation propRelation =
+                    (Condition.UserpropRelation) cond;
+            Id propId = propRelation.key();
+            Set<Object> values = this.getIndexValues(element.id());
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:594]: rename to fieldValues

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 35]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+        private final Map<Id, LeftIndex> leftIndexMap;
+        private final Map<Id, Set<Object>> element2IndexValues;
+
+        public Element2IndexValueMap(Id propertyId) {
+            this.propertyId = propertyId;
+            this.element2IndexValues = new HashMap<>();
+            this.leftIndexMap = new HashMap<>();
+        }
+
+        public void addValue(Id id, Object indexValue) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:563]: addIndexValue

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 36]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+                }
+            }
+            return false;
+        }
+    }
+
+    public static class LeftIndex {
+
+        private Object value;
+        private Id property;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:647]: set final

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 37]
```diff
@@ -613,6 +613,7 @@ private IdHolder doIndexQueryBatch(IndexLabel indexLabel,
                     this.removeExpiredIndexIfNeeded(index, query.showExpired());
                     ids.addAll(index.elementIds());
                     Query.checkForceCapacity(ids.size());
+                    recordIndexValue(query, index, indexLabel);
```
[the remark this answers is not in the document]
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:617]: this.recordIndexValue

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 38]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+            } else {
+                this.element2IndexValues.put(id, Sets.newHashSet(indexValue));
+            }
+        }
+
+        public Set<Object> getIndexValues(Id elementId){
+            return this.element2IndexValues.get(elementId);
+        }
+
+        public void addLeftIndex(Id property, Object indexVaue,
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:575]: Set\<Object> indexVaues?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 39]
```diff
@@ -118,7 +118,7 @@ public GraphIndexTransaction(HugeGraphParams graph, BackendStore store) {
 
     protected Id asyncRemoveIndexLeft(ConditionQuery query,
                                       HugeElement element) {
-        LOG.info("Remove left index: {}, query: {}", element, query);
+        LOG.debug("Remove left index: {}, query: {}", element, query);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:121]: set info level and don't call this method such many times

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 40]
```diff
@@ -408,6 +409,93 @@ public void testAddVertexWithInvalidPropertyList() {
...
+
+        schema.propertyKey("updateTime").asLong().create();
+
+        schema.vertexLabel("soft").properties("name", "updateTime")
+              .primaryKeys("name").create();
+
+        schema.indexLabel("softByUpdateTime").onV("soft").range()
+              .by("updateTime").create();
+
+        for (int i = 1; i <= 2000; i++) {
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:425]: define const var and set a small value

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 41]
```diff
@@ -448,11 +448,11 @@ public boolean test(HugeElement element) {
                 return false;
             }
 
-            if (this.element2IndexValueMap == null) {
-                continue;
-            }
-            if (!this.element2IndexValueMap.validRangeIndex(element, cond)) {
-                return false;
+            if (this.element2IndexValueMap != null) {
+                if (!this.element2IndexValueMap
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:452]:
```
this.element2IndexValueMap != null &&
!this.element2IndexValueMap.validRangeIndex(element, cond)
```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 42]
```diff
@@ -629,30 +639,20 @@ private boolean numberEquals(Object number1, Object number2) {
...
-        }
     }
 
-    public static class LeftIndex {
+    public static final class LeftIndex {
 
-        private Object value;
-        private Id property;
+        private final Set<Object> values;
+        private final Id property;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:647]: indexFieldName?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 43]
```diff
@@ -629,30 +639,20 @@ private boolean numberEquals(Object number1, Object number2) {
...
-            return false;
-        }
     }
 
-    public static class LeftIndex {
+    public static final class LeftIndex {
 
-        private Object value;
-        private Id property;
+        private final Set<Object> values;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:646]: indexFieldValues?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 44]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+
+        public boolean validRangeIndex(HugeElement element,
+                                        Condition cond) {
+            // Not UserpropRelation
+            if (!(cond instanceof Condition.UserpropRelation)) {
+                return true;
+            }
+
+            Condition.UserpropRelation propRelation =
+                    (Condition.UserpropRelation) cond;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:592]: align with propRelation

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 45]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+                this.element2IndexValues.put(id, Sets.newHashSet(indexValue));
+            }
+        }
+
+        public Set<Object> getIndexValues(Id elementId){
+            return this.element2IndexValues.get(elementId);
+        }
+
+        public void addLeftIndex(Id property, Set<Object> indexValues,
+                                  Id elementId) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:576]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 46]
```diff
@@ -522,4 +547,116 @@ private static Object convertNumberIfNeeded(Object value) {
...
+            this.leftIndexMap.put(elementId, new LeftIndex(indexValues, property));
+        }
+
+        public LeftIndex getLeftIndex(Id elementId) {
+            return this.leftIndexMap.get(elementId);
+        }
+
+        public boolean validRangeIndex(HugeElement element,
+                                        Condition cond) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:585]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 47]
```diff
@@ -629,30 +639,20 @@ private boolean numberEquals(Object number1, Object number2) {
...
-        public LeftIndex(Object value, Id property) {
-            this.value = value;
+        public LeftIndex(Set<Object> values, Id property) {
+            this.values = values;
             this.property = property;
         }
 
-        public Object value() {
-            return value;
+        public Set<Object> values() {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:654]: ditto

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 48]
```diff
@@ -1598,53 +1625,38 @@ protected long removeIndexLeft(ConditionQuery query,
...
             long count = 0;
-            // Construct index ConditionQuery
-            Set<MatchedIndex> matchedIndexes = tx.collectMatchedIndexes(query);
-            IndexQueries queries = null;
-            Id elementLabelId = element.schemaLabel().id();
-            for (MatchedIndex index : matchedIndexes) {
-                if (index.schemaLabel().id().equals(elementLabelId)) {
-                    queries = index.constructIndexQueries(query);
-                    break;
+            if (this.leftIndex != null) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1629]: return first if leftIndex==null

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 49]
```diff
@@ -1598,53 +1625,38 @@ protected long removeIndexLeft(ConditionQuery query,
...
-                        }
-                    }
-                } finally {
-                    CloseableIterator.closeIterator(it);
-                }
+        private IndexLabel findMatchedIndexLabel(ConditionQuery query) {
+            IndexLabel indexLabel = null;
+            Set<MatchedIndex> matchedIndexes = tx.collectMatchedIndexes(query);
+            for (MatchedIndex index : matchedIndexes) {
+               for (IndexLabel label :  index.indexLabels()){
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1652]: two spaces "label : index"

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 50]
```diff
@@ -408,6 +409,95 @@ public void testAddVertexWithInvalidPropertyList() {
...
+
+        schema.propertyKey("updateTime").asLong().create();
+
+        schema.vertexLabel("soft").properties("name", "updateTime")
+              .primaryKeys("name").create();
+
+        schema.indexLabel("softByUpdateTime").onV("soft").range()
+              .by("updateTime").create();
+
+        final long TEST_DATA_COUNT = 10L;
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:425]: lowercase

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 42 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:647]: indexFieldId

**Comment by imbajin** [comment]
@jadepeng could u rebase the master branch to fix the code coverage problem? (refer #1529)

**Comment by jadepeng** [comment]
> @jadepeng could u rebase the master branch to fix the code coverage CI problem? (refer #1529)

already rebase master

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 51]
```diff
@@ -1598,55 +1625,42 @@ protected long removeIndexLeft(ConditionQuery query,
...
             return count;
         }
 
+        private IndexLabel findMatchedIndexLabel(ConditionQuery query) {
+            IndexLabel indexLabel = null;
+            Set<MatchedIndex> matchedIndexes = tx.collectMatchedIndexes(query);
+            for (MatchedIndex index : matchedIndexes) {
+               for (IndexLabel label : index.indexLabels()){
+                   if (label.indexField().equals(leftIndex.indexField())){
+                       indexLabel = label;
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1656]: return label

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 52]
```diff
@@ -408,6 +409,97 @@ public void testAddVertexWithInvalidPropertyList() {
...
+
+        count = graph.traversal().V()
+                     .has("soft", "updateTime",
+                          ConditionP.gt(0))
+                     .limit(-1)
+                     .count()
+                     .next();
+        Assert.assertEquals(testDataCount, count);
+    }
+
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:455]: add one test:
vertex label 'person' has two property 'age' and 'score' with range index, and construct left index for both. Then query by 'age' and 'score' by range.

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 53]
```diff
@@ -522,4 +548,150 @@ private static Object convertNumberIfNeeded(Object value) {
...
+            return !propId.equals(this.mainIndexField) || hasRightValue;
+        }
+
+        private void initMainIndexFiled() {
+            int maxElementSize = 0;
+            for (Id indexField : this.filed2IndexValues.keySet()) {
+                int elementSize = this.filed2IndexValues.get(indexField).size();
+                if (elementSize > maxElementSize) {
+                    this.mainIndexField = indexField;
+                    maxElementSize = elementSize;
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:649]: what's mainIndexField for and why elements size determine mainIndexField?

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 53 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java]: 是指doJointIndex里选择的range索引，之前考虑的可以通过数量来判断，发现还是存在问题
现在在doJointIndex里，记录了最后选择的range index

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 54]
```diff
@@ -522,4 +569,144 @@ private static Object convertNumberIfNeeded(Object value) {
...
+            Set<Object> fieldValues = this.getIndexValues(propId, element.id());
+            if (fieldValues == null) {
+                // Not range index
+                return true;
+            }
+
+            HugeProperty<Object> hugeProperty = element.getProperty(propId);
+            if (hugeProperty == null) {
+                // Property value has been deleted
+                this.addLeftIndex(propId, fieldValues, element.id());
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:642]: remove from filed2IndexValues when add LeftIndex to ensure filed2IndexValuesw won't be too large

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 55]
```diff
@@ -1598,55 +1639,43 @@ protected long removeIndexLeft(ConditionQuery query,
...
-                                tx.doAppend(serializer.writeIndex(index));
-                                tx.commit();
-                            } else {
-                                count++;
-                            }
-                        }
-                    }
-                } finally {
-                    CloseableIterator.closeIterator(it);
+            for (ConditionQuery.LeftIndex leftIndex : this.leftIndexes) {
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1647]: remove LeftIndex after constructing remove job

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java [hunk 56]
```diff
@@ -522,4 +569,144 @@ private static Object convertNumberIfNeeded(Object value) {
         INDEX,
         INDEX_FILTER
     }
+
+    public static final class Element2IndexValueMap {
+
+        private final Map<Id, Set<LeftIndex>> leftIndexMap;
+        private final Map<Id, Map<Id, Set<Object>>> filed2IndexValues;
+        private Id selectedIndexField;
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:577]: seems not work as expected. JointQuery will do index query one by one before test element. So `selectedIndexField` will always be same.

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java (hunk 56 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/query/ConditionQuery.java:577]:
```
IdHolder holder = this.doIndexQuery(indexLabel, query);
            if (resultHolder == null) {
                resultHolder = holder;
                this.storeSelectedIndexField(indexLabel, query);
            }
            assert this.indexIntersectThresh > 0; // default value is 1000
            Set<Id> ids = ((BatchIdHolder) holder).peekNext(
                          this.indexIntersectThresh).ids();
            if (ids.size() >= this.indexIntersectThresh) {
                // Transform into filtering
                filtering = true;
                query.optimized(OptimizedType.INDEX_FILTER);
            } else if (filtering) {
                assert ids.size() < this.indexIntersectThresh;
                resultHolder = holder;
                this.storeSelectedIndexField(indexLabel, query);
                break;
            }
```

Case:
- the first index's ids size > indexIntersectThresh
- the second index's ids size < indexIntersectThresh

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 57]
```diff
@@ -1598,55 +1639,45 @@ protected long removeIndexLeft(ConditionQuery query,
...
+                Set<Object> indexValues = leftIndex.indexFieldValues();
+                IndexLabel indexLabel = findMatchedIndexLabel(query, leftIndex);
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:1649]: `IndexLabel indexLabel = this.findMatchedIndexLabel(query, leftIndex);`

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 58]
```diff
@@ -408,6 +409,139 @@ public void testAddVertexWithInvalidPropertyList() {
...
+        count = graph.traversal().V()
+                     .hasLabel("developer")
+                     .has("age", ConditionP.gt(0))
+                     .has("score", ConditionP.gt(0))
+                     .limit(-1)
+                     .count()
+                     .next();
+
+        Assert.assertEquals(testDataCount, count);
```
Comment (zhoney) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:495]: in debug mode, stop here, you will see still some left range index.(in table hugegraph.g_ii when using Cassandra backend )

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java (hunk 58 above)
Comment (jadepeng) [reply hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:495]: 由于index_intersect_threshold的限制，其中一个索引（age）只读取了index_intersect_threshold个记录，所以只能保障（score）的left索引全部删除

后续再通过age查询，可以正确删除遗留索引

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 59]
```diff
@@ -493,6 +493,23 @@ public void testRemoveLeftRangeIndex(){
...
+
+        count = graph.traversal().V()
+                     .hasLabel("developer")
+                     .has("age", ConditionP.gt(0))
+                     .limit(-1)
+                     .count()
+                     .next();
+        // Debug stop here to see whether the left index be correctly determined
+        Assert.assertEquals(testDataCount, count);
+
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:512]: unused empty line

File: hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java [hunk 60]
```diff
@@ -493,6 +493,23 @@ public void testRemoveLeftRangeIndex(){
                      .next();
 
         Assert.assertEquals(testDataCount, count);
+
+        // Wait left index to be removed
+        try {
+            Thread.sleep(2000);
+        } catch (InterruptedException e) {
+            e.printStackTrace();
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/core/VertexCoreTest.java:501]: let testRemoveLeftRangeIndex throws InterruptedException

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 61]
```diff
@@ -621,6 +624,20 @@ private IdHolder doJointIndex(IndexQueries queries) {
         }
     }
 
+    private void storeSelectedIndexField(IndexLabel indexLabel,
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:627]: can be deleted now

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 62]
```diff
@@ -589,6 +590,7 @@ private IdHolder doJointIndex(IndexQueries queries) {
             IdHolder holder = this.doIndexQuery(indexLabel, query);
             if (resultHolder == null) {
                 resultHolder = holder;
+                this.storeSelectedIndexField(indexLabel, query);
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:593]: can be deleted now

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java [hunk 63]
```diff
@@ -600,6 +602,7 @@ private IdHolder doJointIndex(IndexQueries queries) {
             } else if (filtering) {
                 assert ids.size() < this.indexIntersectThresh;
                 resultHolder = holder;
+                this.storeSelectedIndexField(indexLabel, query);
```
Comment (zhoney) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:605]: can be deleted now

**Review by zhoney — CHANGES_REQUESTED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java (hunk 61 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:627]: selectedIndexField is meaningful,
if delete this, VertexCoreTests Line 499 will throw AssertionError

```
Exception in thread "hugegraph-shutdown" com.baidu.hugegraph.HugeException: Failed to shutdown
	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:144)
	at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 1
	at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:180)
	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:140)
	... 2 more

java.lang.AssertionError: 
Expected :10
Actual   :9
```

原因在于选择的是`score`，只能用score来判断数据是否满足条件；
`age`的索引未读取完成，只能用来删除过期说明，不能判断数据是否OK

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 64]
```diff
@@ -1645,6 +1665,14 @@ private boolean rightResultFromIndexQuery(Query query, HugeElement elem) {
 
         ConditionQuery cq = (ConditionQuery) query;
         if (cq.optimized() == OptimizedType.NONE || cq.test(elem)) {
+            if (cq.elementHasLeftIndex(elem.id())) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:1668]: existLeftIndex

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 65]
```diff
@@ -1548,14 +1575,7 @@ private void checkVertexExistIfCustomizedId(Map<Id, HugeVertex> vertices) {
...
             HugeVertex newVertex = vertices.get(existedVertex.id());
-            if (!existedVertex.label().equals(newVertex.label())) {
-                throw new HugeException(
-                          "The newly added vertex with id:'%s' label:'%s' " +
-                          "is not allowed to insert, because already exist " +
-                          "a vertex with same id and different label:'%s'",
-                          newVertex.id(), newVertex.label(),
-                          existedVertex.label());
-            }
+            checkLabel(existedVertex, newVertex);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:1578]: don't need to add a method?

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 66]
```diff
@@ -351,6 +359,25 @@ protected void prepareAdditions(Map<Id, HugeVertex> addedVertices,
...
+        if (ids.isEmpty()) {
+            return;
+        }
+        IdQuery idQuery = new IdQuery(HugeType.VERTEX, ids);
+        Iterator<HugeVertex> results = this.queryVerticesFromBackend(idQuery);
+        try {
+            while (results.hasNext()) {
+                HugeVertex existedVertex = results.next();
+                HugeVertex newVertex = vertices.get(existedVertex.id());
+                checkLabel(existedVertex, newVertex);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:373]: ignore the label here since checkVertexExistIfCustomizedId() will do the check

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 67]
```diff
@@ -351,6 +359,25 @@ protected void prepareAdditions(Map<Id, HugeVertex> addedVertices,
         }
     }
 
+    private void removeLeftIndex(Map<Id, HugeVertex> vertices) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:362]: move to line 1583 and rename to removeLeftIndexIfNeeded

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java (hunk 61 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphIndexTransaction.java:627]: 举个例子就是
age： {id:1,错误value} {id2: 正确value}
score：{ id1：正确value} {id2： 正确value}

假如选择的是score作为查询索引
age 会把id1 错误过滤掉
而后续通过score查询，会导致id 1查询不到

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java [hunk 68]
```diff
@@ -1620,6 +1608,23 @@ private void lockForUpdateProperty(SchemaLabel schemaLabel,
         }
     }
 
+    private void removeLeftIndexIfNeeded(Map<Id, HugeVertex> vertices) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:1611]: can mock and test it? use Whitebox to set removeLeftIndexOnOverwrite=true

**Review by javeme — APPROVED** [review]

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java (hunk 68 above)
Comment (jadepeng) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/GraphTransaction.java:1611]: add test, but seems not work

**Review by zhoney — APPROVED** [review]

**Comment by javeme** [comment]
failure test of cassandra backend:
```java
Error:  Tests run: 713, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 500.427 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
Error:  testRemoveLeftRangeIndex(com.baidu.hugegraph.core.VertexCoreTest)  Time elapsed: 2.742 s  <<< FAILURE!
java.lang.AssertionError: expected:<10> but was:<6>
	at com.baidu.hugegraph.core.VertexCoreTest.testRemoveLeftRangeIndex(VertexCoreTest.java:536)

2021-07-28 11:37:05 [hugegraph-shutdown] [INFO] c.b.h.HugeGraph - HugeGraph is shutting down
Error: -28 11:37:05 [hugegraph-shutdown] [ERROR] c.b.h.HugeGraph - Error while shutdown
java.lang.AssertionError: 2
	at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:180) ~[classes/:?]
	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:140) ~[classes/:?]
	at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Error: Exception in thread "hugegraph-shutdown" com.baidu.hugegraph.HugeException: Failed to shutdown
	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:144)
	at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 2
	at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:180)
	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:140)
	... 2 more
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    VertexCoreTest.testRemoveLeftRangeIndex:536 expected:<10> but was:<6>
[INFO] 
Error:  Tests run: 713, Failures: 1, Errors: 0, Skipped: 21
```

**Comment by jadepeng** [comment]
> failure test of cassandra backend:
> 
> ```java
> Error:  Tests run: 713, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 500.427 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
> Error:  testRemoveLeftRangeIndex(com.baidu.hugegraph.core.VertexCoreTest)  Time elapsed: 2.742 s  <<< FAILURE!
> java.lang.AssertionError: expected:<10> but was:<6>
> 	at com.baidu.hugegraph.core.VertexCoreTest.testRemoveLeftRangeIndex(VertexCoreTest.java:536)
> 
> 2021-07-28 11:37:05 [hugegraph-shutdown] [INFO] c.b.h.HugeGraph - HugeGraph is shutting down
> Error: -28 11:37:05 [hugegraph-shutdown] [ERROR] c.b.h.HugeGraph - Error while shutdown
> java.lang.AssertionError: 2
> 	at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:180) ~[classes/:?]
> 	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:140) ~[classes/:?]
> 	at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52) ~[classes/:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
> Error: Exception in thread "hugegraph-shutdown" com.baidu.hugegraph.HugeException: Failed to shutdown
> 	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:144)
> 	at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.AssertionError: 2
> 	at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:180)
> 	at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:140)
> 	... 2 more
> [INFO] 
> [INFO] Results:
> [INFO] 
> Error:  Failures: 
> Error:    VertexCoreTest.testRemoveLeftRangeIndex:536 expected:<10> but was:<6>
> [INFO] 
> Error:  Tests run: 713, Failures: 1, Errors: 0, Skipped: 21
> ```

fixed

**Review by zhoney — APPROVED** [review]
