### PR TITLE
Fix override vertex/edge on some backends

### LINKED ISSUE #792: hugegraph-load重复导入顶点，如何移除旧数据中不要的顶点属性
使用hugegraph-load导入了顶点数据，此时顶点中有has_Category这个属性，
现在在JSON数据集中移除掉has_Category这个属性后，又用hugegraph-load导了一遍，此时查询顶点没有看到has_Category这个属性，但过了一晚后这个属性又可以在顶点上查询到，请问这是什么原因？有什么方法可以删除大量顶点的某个属性？

### Expected behavior 期望表现
hugegraph-loader重复导入顶点，属性以最新的数据集为准。
使用过https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html中的update_strategies=overwrite，由于是旧数据有该属性，新数据没有该属性，貌似没有被真正覆盖。

### Actual behavior 实际表现
第二次导入，当时查询顶点没有看到被移除的属性，过一段时间这个属性又出现了。
image

### PR DESCRIPTION
**Pull request by Linary**
Fix #792

Change-Id: Iad461c6742773bd001a1768f83479e1ab429e272

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 1]
```diff
@@ -116,6 +116,22 @@ private String formatPropertyValue(HugeProperty<?> prop) {
...
 
+    private String formatPropertyName() {
+        return HugeType.PROPERTY.string();
+    }
+
+    private String formatPropertyValues(HugeVertex vertex) {
+        StringBuilder sb = new StringBuilder(256 * vertex.getProperties().size());
+        // Vertex properties
+        for (HugeProperty<?> property : vertex.getProperties().values()) {
+            sb.append(VALUE_SPLITOR);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: don't append VALUE_SPLITOR for the first property

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 2]
```diff
@@ -142,6 +158,14 @@ private void parseProperty(String colName, String colValue,
         }
     }
 
+    private void parseProperties(String colValue, HugeVertex vertex) {
+        String[] valParts = colValue.split(VALUE_SPLITOR);
+        // Edge properties
+        for (int i = 1; i < valParts.length; i += 2) {
+            this.parseProperty(valParts[i], valParts[i + 1], vertex);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: i + 1 may be out of bound

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 3]
```diff
@@ -244,29 +268,27 @@ public BackendEntry writeVertex(HugeVertex vertex) {
...
+//
+//        // Write label (NOTE: maybe just with edges if label is null)
+//        if (vertex.schemaLabel() != null) {
+//            entry.column(this.formatSyspropName(HugeKeys.LABEL),
+//                         writeId(vertex.schemaLabel().id()));
+//        }
+//
+//        entry.column(this.formatPropertyName(prop),
+//                     this.formatPropertyValue(prop));
+//        return entry;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: remove it

File: hugegraph-test/src/main/java/com/baidu/hugegraph/unit/serializer/BinarySerializerTest.java [hunk 4]
```diff
@@ -30,11 +30,11 @@
 import com.baidu.hugegraph.unit.BaseUnitTest;
 import com.baidu.hugegraph.unit.FakeObjects;
 
-public class BinaryInlineSerializerTest extends BaseUnitTest {
+public class BinarySerializerTest extends BaseUnitTest {
```
Comment (javeme) [inline hugegraph-test/src/main/java/com/baidu/hugegraph/unit/serializer/BinarySerializerTest.java]: also add BinaryScatterSerializerTest

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java [hunk 5]
```diff
@@ -367,23 +367,34 @@ public BackendEntry writeVertex(HugeVertex vertex) {
...
         // Write vertex label
-        entry.column(this.formatLabel(vertex));
+        buffer.writeId(vertex.schemaLabel().id());
 
-        // Write all properties of a Vertex
-        for (HugeProperty<?> prop : vertex.getProperties().values()) {
-            entry.column(this.formatProperty(prop));
-        }
+        // Write all properties of the vertex
+        this.formatProperties(vertex.getProperties().values(), buffer);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java]: update vertex.get()

File: hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBTables.java [hunk 6]
```diff
@@ -120,6 +120,16 @@ public IndexLabel(String database) {
...
+
+        @Override
+        protected BackendColumnIterator queryById(Session session, Id id) {
+            byte[] value = session.get(this.table(), id.asBytes());
+            if (value == null) {
+                return BackendColumnIterator.empty();
+            }
+            BackendColumn col = BackendColumn.of(id.asBytes(), value);
+            return new BackendColumnIteratorWrapper(col);
+        }
```
Comment (javeme) [inline hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBTables.java]: prefer to add a protected method getById() to super class, and just call super.getById() here, also call it from EdgeTable.queryById().

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java [hunk 7]
```diff
@@ -393,21 +404,22 @@ public HugeVertex readVertex(HugeGraph graph, BackendEntry bytesEntry) {
...
-            this.parseColumn(col, vertex);
+            if (entry.type().isEdge()) {
+                // NOTE: the id is vertex type even if query edge
+                // Parse vertex edges
+                this.parseColumn(col, vertex);
+            } else {
+                // Parse vertex properties
+                assert entry.columnsSize() == 1 : entry.columnsSize();
+                this.parseVertex(col.value, vertex);
+            }
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java]:
```
diff --git a/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinaryInlineSerializer.java b/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinaryInlineSerializer.java
index b94d0608..b2481aa6 100644
--- a/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinaryInlineSerializer.java
+++ b/hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinaryInlineSerializer.java
@@ -72,11 +72,13 @@ public class BinaryInlineSerializer extends BinarySerializer {
 
         // Parse all properties and edges of a Vertex
         for (BackendColumn col : entry.columns()) {
-            if (id.edge()) {
+            // NOTE: the entry id type is vertex even if entry type is edge
+            if (entry.type().isEdge()) {
                 // Parse vertex edges
                 this.parseColumn(col, vertex);
             } else {
                 // Parse vertex properties
+                assert entry.type().isVertex();
                 assert entry.columnsSize() == 1 : entry.columnsSize();
                 this.parseVertex(col.value, vertex);
             }
```

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java [hunk 8]
```diff
@@ -393,21 +404,22 @@ public HugeVertex readVertex(HugeGraph graph, BackendEntry bytesEntry) {
...
         Id id = entry.id().origin();
-        HugeVertex vertex = new HugeVertex(graph, id, label);
+        Id vid = id.edge() ? ((EdgeId) id).ownerVertexId() : id;
+        HugeVertex vertex = new HugeVertex(graph, vid, VertexLabel.NONE);
 
         // Parse all properties and edges of a Vertex
         for (BackendColumn col : entry.columns()) {
-            this.parseColumn(col, vertex);
+            if (entry.type().isEdge()) {
+                // NOTE: the id is vertex type even if query edge
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java]: This bug was introduced from https://github.com/hugegraph/hugegraph/pull/680/files#diff-e46dfe3b041d128cc0a4657fe901a3b7R75

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java [hunk 9]
```diff
@@ -393,21 +404,22 @@ public HugeVertex readVertex(HugeGraph graph, BackendEntry bytesEntry) {
...
+                // Parse vertex edges
+                this.parseColumn(col, vertex);
+            } else {
+                // Parse vertex properties
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java]: assert entry.type().isVertex();

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java (hunk 8 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/BinarySerializer.java]: // NOTE: the entry id type is vertex even if entry type is edge

File: hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBTables.java (hunk 6 above)
Comment (javeme) [reply hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBTables.java]: prefer to add a protected method getById() to super class, and just call super.getById() here, also call it from EdgeTable.queryById().

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 10]
```diff
@@ -142,6 +162,21 @@ private void parseProperty(String colName, String colValue,
...
+    private void parseProperties(String colValue, HugeVertex vertex) {
+        if (colValue == null || colValue.isEmpty()) {
+            return;
+        }
+        String[] valParts = colValue.split(VALUE_SPLITOR);
+        // Edge properties
+        for (int i = 0; i < valParts.length; i += 2) {
+            try {
+                this.parseProperty(valParts[i], valParts[i + 1], vertex);
+            } catch (ArrayIndexOutOfBoundsException e) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: remove the catch after check valParts.length % 2 == 0

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 11]
```diff
@@ -142,6 +162,21 @@ private void parseProperty(String colName, String colValue,
         }
     }
 
+    private void parseProperties(String colValue, HugeVertex vertex) {
+        if (colValue == null || colValue.isEmpty()) {
+            return;
+        }
+        String[] valParts = colValue.split(VALUE_SPLITOR);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: E.checkState(valParts.length % 2 == 0)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 12]
```diff
@@ -142,6 +162,21 @@ private void parseProperty(String colName, String colValue,
...
+        // Edge properties
+        for (int i = 0; i < valParts.length; i += 2) {
+            try {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: assert i + 1 < valParts.length

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java [hunk 13]
```diff
@@ -116,6 +116,26 @@ private String formatPropertyValue(HugeProperty<?> prop) {
         return JsonUtil.toJson(prop.value());
     }
 
+    private String formatPropertyName() {
+        return HugeType.PROPERTY.string();
+    }
+
+    private String formatPropertyValues(HugeVertex vertex) {
+        int size = vertex.getProperties().size();
+        StringBuilder sb = new StringBuilder(256 * size);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/serializer/TextSerializer.java]: 64 * size is ok
