### PR TITLE
make create index label return async job if exists

### LINKED ISSUE #32: Lock error thrown when modifying schema and data dynamically
The schema created at the beginning can't satisfy our requirement, so we have to modify the schema to load data into the database. When we modify the schema and invoke setProperty method, the following exception thrown:
```
com.baidu.hugegraph.exception.ServerException: Lock [il_delete:35] is locked by other operation
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:142) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.append(VertexAPI.java:70) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.driver.GraphManager.appendVertexProperty(GraphManager.java:143) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.setProperty(Vertex.java:73) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.property(Vertex.java:63) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.property(Vertex.java:30) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugedragon.repository.graphdb.hugegraph.HugeGraphElement.setProperty(HugeGraphElement.java:118) ~[classes/:?]
	... 19 more
```
### Steps to reproduce

- Create a vertex label
- Add a property key 
- Add a property with property key created in last step in the vertex label
- Set value for the new created property

### Environments
- hugegraph-client 1.5.8
- hugegraph-core 0.7.4

### PR DESCRIPTION
**Pull request by zhoney**
fixed #32

Change-Id: I8e23bd0dfcbe65d8f580f957143fcc1802c879f6

### CODE REVIEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java [hunk 1]
```diff
@@ -202,6 +203,33 @@ public boolean close() {
         return result;
     }
 
+    public <V> Iterator<HugeTask<V>> task(List<Id> idList) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java]: rename to tasks(ids), and move to line 189

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java [hunk 2]
```diff
@@ -202,6 +203,33 @@ public boolean close() {
...
+                taskNotInMem.add(id);
+            }
+        }
+        @SuppressWarnings("unchecked")
+        ExtendableIterator<HugeTask<V>> iterator;
+        if (taskInMem.isEmpty()) {
+            iterator = new ExtendableIterator<>();
+        } else {
+            iterator = new ExtendableIterator<>(taskInMem.iterator());
+        }
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java]: add a method findTask(ids)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java [hunk 3]
```diff
@@ -240,6 +268,23 @@ public boolean close() {
...
 
+    private <V> boolean completed(HugeTask<V> task) {
+        if (!task.completed()) {
+            return false;
+        }
+        // task itself is completed
+        if (task.children() == null || task.children().isEmpty()) {
+            return true;
+        }
+        for (Id id : task.children()) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTaskScheduler.java]: prefer to update status of patent task when a task is completed, and just return status status of task itself when query task status

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java [hunk 4]
```diff
@@ -66,25 +69,41 @@
...
+            } else {
+                itor = scheduler.findTask(parseStatus(status), limit);
+            }
         }
 
         List<Object> tasks = new ArrayList<>();
         while (itor.hasNext()) {
             tasks.add(itor.next().asMap(false));
         }
+        if (limit != NO_LIMIT && tasks.size() > limit) {
```
[the remark this answers is not in the document]
Comment (zhoney) [reply hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java]: if has "ids" argument, "status" must be null and "limit" must be 100

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskScheduler.java [hunk 5]
```diff
@@ -192,6 +193,36 @@ public boolean close() {
...
+        if (taskInMem.isEmpty()) {
+            iterator = new ExtendableIterator<>();
+        } else {
+            iterator = new ExtendableIterator<>(taskInMem.iterator());
+        }
+        iterator.extend(this.findTasks(taskIdsNotInMem));
+        return iterator;
+    }
+
+    public <V> Iterator<HugeTask<V>> findTasks(List<Id> ids) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskScheduler.java]: move the method to line 241

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java [hunk 6]
```diff
@@ -250,6 +254,35 @@ protected void setException(Throwable e) {
...
     }
 
+    protected boolean checkDependencies() {
+        if (this.dependencies == null || this.dependencies.isEmpty()) {
+            return true;
+        }
+        for (Id dependency : this.dependencies) {
+            HugeTask task = this.callable.scheduler().task(dependency);
+            if (!task.completed()) {
+                // dependent task not completed, re-schedule self
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: uppercase

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java [hunk 7]
```diff
@@ -291,6 +325,9 @@ protected void property(String key, Object value) {
             case P.RESULT:
                 this.result = (String) value;
                 break;
+            case P.DEPENDENCIES:
+                this.dependencies = (Set<Id>) value;
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: better to call depends with for-loop

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java [hunk 8]
```diff
@@ -17,32 +17,34 @@
...
 
     private static final String SPLITOR = ":";
 
     protected HugeType schemaType() {
         String name = this.task().name();
         String[] parts = name.split(SPLITOR);
-        E.checkState(parts.length == 2 && parts[0] != null,
-                     "Task name should be formatted to String 'TYPE:ID', " +
-                     "but got '%s'", name);
+        E.checkState(parts.length >= 3 && parts[0] != null,
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java]: name.split(SPLITOR, 3)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java [hunk 9]
```diff
@@ -17,32 +17,34 @@
...
         return HugeType.valueOf(parts[0]);
     }
 
     protected Id schemaId() {
         String name = this.task().name();
         String[] parts = name.split(SPLITOR);
-        E.checkState(parts.length == 2 && parts[1] != null,
-                     "Task name should be formatted to String 'TYPE:ID', " +
-                     "but got '%s'", name);
+        E.checkState(parts.length >= 3 && parts[1] != null,
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java]: ditto

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java [hunk 10]
```diff
@@ -117,7 +139,7 @@ public void delete(@Context GraphManager manager,
     @PUT
     @Timed
     @Path("{id}")
-    @Status(Status.ACCEPTED)
+    @StatusFilter.Status(StatusFilter.Status.ACCEPTED)
```
Comment (javeme) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java]: keep origin

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/SchemaTransaction.java [hunk 11]
```diff
@@ -213,14 +214,15 @@ public IndexLabel getIndexLabel(String name) {
     public Id removeIndexLabel(Id id) {
         LOG.debug("SchemaTransaction remove index label '{}'", id);
         SchemaCallable callable = new IndexLabelRemoveCallable();
-        return asyncRun(this.graph(), HugeType.INDEX_LABEL, id, callable);
+        return asyncRun(this.graph(), HugeType.INDEX_LABEL, id, callable, null);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/SchemaTransaction.java]: add an asyncRun() method which is no dependencies param

File: hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/SchemaTransaction.java [hunk 12]
```diff
@@ -213,14 +214,15 @@ public IndexLabel getIndexLabel(String name) {
...
     }
 
-    public Id rebuildIndex(SchemaElement schema) {
+    public Id rebuildIndex(SchemaElement schema, Set<Id> dependencies) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/SchemaTransaction.java]: add method rebuildIndex(SchemaElement schema)

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java [hunk 13]
```diff
@@ -67,8 +67,8 @@ public String create(@Context GraphManager manager,
 
         HugeGraph g = graph(manager, graph);
         IndexLabel.Builder builder = jsonIndexLabel.convert2Builder(g);
-        IndexLabel indexLabel = builder.create();
-        return manager.serializer(g).writeIndexlabel(indexLabel);
+        IndexLabel.CreatedIndexLabel cil = builder.createWithTask();
```
Comment (javeme) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java]: rename to il

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java [hunk 14]
```diff
@@ -57,6 +60,11 @@ public JobBuilder(final HugeGraph graph) {
         return this;
     }
 
+    public JobBuilder<T> dependencies(Set<Id> dependencies) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java]: maybe it's ImmutableSet

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java [hunk 15]
```diff
@@ -258,6 +291,7 @@ protected void status(TaskStatus status) {
         this.status = status;
     }
 
+    @SuppressWarnings("unchecked")
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: unnecessary

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/EdgeLabelBuilder.java [hunk 16]
```diff
@@ -198,7 +198,7 @@ public Id rebuildIndex() {
         if (edgeLabel == null) {
             return null;
         }
-        return this.transaction.rebuildIndex(edgeLabel);
+        return this.transaction.rebuildIndex(edgeLabel, null);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/EdgeLabelBuilder.java]: call rebuildIndex(SchemaElement schema)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java [hunk 17]
```diff
@@ -143,7 +168,7 @@ public Id rebuild() {
         if (indexLabel == null) {
             return null;
         }
-        return this.transaction.rebuildIndex(indexLabel);
+        return this.transaction.rebuildIndex(indexLabel, null);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java]: call rebuildIndex(SchemaElement schema)

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/VertexLabelBuilder.java [hunk 18]
```diff
@@ -187,7 +187,7 @@ public Id rebuildIndex() {
         if (vertexLabel == null) {
             return null;
         }
-        return this.transaction.rebuildIndex(vertexLabel);
+        return this.transaction.rebuildIndex(vertexLabel, null);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/VertexLabelBuilder.java]: ditto

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java (hunk 13 above)
Comment (zhoney) [reply hugegraph-api/src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java]: done

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java (hunk 15 above)
Comment (zhoney) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: line 329 needs it.
for (Id id : (Set<Id>) value) {

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java (hunk 14 above)
Comment (zhoney) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java]: you are right

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java [hunk 19]
```diff
@@ -57,6 +61,11 @@ public JobBuilder(final HugeGraph graph) {
         return this;
     }
 
+    public JobBuilder<T> dependencies(ImmutableSet<Id> dependencies) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/job/JobBuilder.java]: Set<Id> dependencies

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java [hunk 20]
```diff
@@ -105,16 +111,36 @@ public IndexLabel create() {
...
 
         // Create index label
         indexLabel = this.build();
         indexLabel.status(SchemaStatus.CREATING);
         this.transaction.addIndexLabel(schemaLabel, indexLabel);
 
         // TODO: use event to replace direct call
-        this.rebuildIndexIfNeeded(schemaLabel, indexLabel);
+        Id rebuildTask = this.rebuildIndexIfNeeded(
+           schemaLabel, indexLabel, ImmutableSet.copyOf(removeTasks));
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java]: no need to copy

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (javeme) [reply hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java]: this will lead to unable to query ids with size > 100

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java [hunk 21]
```diff
@@ -75,16 +79,35 @@
...
+                itor = scheduler.findTask(parseStatus(status), limit);
+            }
         }
 
         List<Object> tasks = new ArrayList<>();
         while (itor.hasNext()) {
             tasks.add(itor.next().asMap(false));
         }
+        if (limit != NO_LIMIT && tasks.size() > limit) {
+            tasks = tasks.subList(0, Long.valueOf(limit).intValue());
```
Comment (javeme) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java]: (int) limit

File: hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java (hunk 8 above)
Comment (javeme) [reply hugegraph-core/src/main/java/com/baidu/hugegraph/job/schema/SchemaCallable.java]: use name.split(SPLITOR, 3) instead of >=3

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java [hunk 22]
```diff
@@ -105,16 +110,36 @@ public IndexLabel create() {
...
+        IndexLabel.CreatedIndexLabel createdIndexLabel = this.createWithTask();
+        Id task = createdIndexLabel.task();
+        IndexLabel indexLabel = createdIndexLabel.indexLabel();
+        if (task == null) {
+            E.checkNotNull(indexLabel, "index label");
+            return indexLabel;
+        }
+        TaskScheduler scheduler = this.transaction.graph().taskScheduler();
+        try {
+            scheduler.waitUntilTaskCompleted(task, 30L);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java]: add TOTO get timeout from config

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java [hunk 23]
```diff
@@ -104,15 +106,15 @@ public Id parent() {
...
-        return Collections.unmodifiableList(this.children);
+    public Set<Id> dependencies() {
+        return Collections.unmodifiableSet(this.dependencies);
     }
 
-    public void child(Id id) {
-        if (this.children == null) {
-            this.children = new ArrayList<>();
+    public void depends(Id id) {
+        if (this.dependencies == null) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: check status must be NEW

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskScheduler.java [hunk 24]
```diff
@@ -208,6 +232,14 @@ public boolean close() {
         return result;
     }
 
+    public <V> Iterator<HugeTask<V>> findTasks(List<Id> ids) {
+        Id[] idArray = ids.toArray(new Id[ids.size()]);
+        Iterator<Vertex> vertices = this.tx().queryVertices((Object) idArray);
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskScheduler.java]: don't call this.tx() in other threads

File: hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java [hunk 25]
```diff
@@ -190,8 +197,10 @@ public String toString() {
     @Override
     public void run() {
         assert this.status.code() < TaskStatus.RUNNING.code();
-        this.status(TaskStatus.RUNNING);
-        super.run();
+        if (this.checkDependencies()) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java]: checkDependenciesSuccess

File: hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java [hunk 26]
```diff
@@ -75,16 +79,35 @@
...
+        if (!ids.isEmpty()) {
+            LOG.debug("Graph [{}] list tasks with ids {}, limit {}",
+                      graph, ids, limit);
+            E.checkArgument(status == null,
+                            "Not support status when query task by ids, " +
+                            "but got status='%s'", status);
+            // Set limit to NO_LIMIT to ignore limit when query task by ids
+            limit = NO_LIMIT;
+            List<Id> idList = ids.stream().map(IdGenerator::of)
+                                 .collect(Collectors.toList());
```
Comment (javeme) [inline hugegraph-api/src/main/java/com/baidu/hugegraph/api/job/TaskAPI.java]: align

File: hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java [hunk 27]
```diff
@@ -334,14 +360,22 @@ private void removeSubIndex(SchemaLabel schemaLabel) {
                 overrideIndexLabelIds.add(id);
             }
         }
+        Set<Id> tasks = InsertionOrderUtil.newSet();
         for (Id id : overrideIndexLabelIds) {
             schemaLabel.removeIndexLabel(id);
-            this.transaction.removeIndexLabel(id);
+            Id task = this.transaction.removeIndexLabel(id);
+            HugeConfig config = this.transaction.graph().configuration();
+            if (!config.get(CoreOptions.SCHEMA_SYNC_DELETION)) {
```
Comment (javeme) [inline hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/IndexLabelBuilder.java]: add if task != null
